### ISSUE TITLE
modal里的select控件，在modal弹出时，select的配置一直保留上一次，没有重置 

### ISSUE THREAD

**Issue by haima95** [amazeui/amazeui#1006]
<div class="am-modal am-modal-prompt" tabindex="-1" id="my-prompt">
  <div class="am-modal-dialog">
    <div class="am-modal-hd">
      <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
    </div>
    <div class="am-modal-bd" style="margin-top:18px;">
   <div class="am-ag">
   <form class="am-form am-form-horizontal" data-am-validator> 
       <div class="am-form-group">
    <label class="am-u-sm-3 am-form-label">爽约</label>
    <div>
       <select data-am-selected={btnWidth:'65%'} id="ontimeType">
     <option value="0">准时到达</option>
     <option value="1">迟到1-29分钟</option>
     <option value="2">迟到30分钟以上</option>
     <option value="3">临时取消</option>
    </select>
    </div>
    </div>
    <div class="am-form-group">
    <label class="am-u-sm-3 am-form-label">讲义</label>
    <div>
       <select data-am-selected={btnWidth:'65%'} id="handoutsType">
     <option value="0">预约人未提前发讲义，老师自带-合格</option>
     <option value="1">预约人未提前发讲义，老师自带-不合格</option>
     <option value="2">预约人未提前发讲义，临时向预约人索要-合格</option>
     <option value="3">预约人未提前发讲义，临时向预约人索要-不合格</option>
     <option value="4">预约人已提前发讲义，老师讲义有更新自带讲义-合格</option>
     <option value="5">预约人已提前发讲义，老师讲义有更新自带讲义-不合格</option>
     <option value="6">预约人已提前发讲义-合格</option>
     <option value="7">预约人已提前发讲义-不合格</option>
    </select>
    </div>
    </div>      

$('#my-prompt').on('open.modal.amui', function(){ 
   addMemoBookid = id;
   if(bookRoomInfo[roomid]['memo'] != null){
       var strTemp = bookRoomInfo[roomid]['memo'].split(",");
       $('#ontimeType').find('option').eq(strTemp[0]).attr('selected', true);
       $('#handoutsType').find('option').eq(strTemp[1]).attr('selected', true);
       $('#recordType').find('option').eq(strTemp[2]).attr('selected', true);
       $('#department').find('option').eq(strTemp[3]).attr('selected', true);
       $('#bookMemo').val(strTemp[4]);
         }else{
       $('#ontimeType').find('option').eq(0).attr('selected', true);
       $('#handoutsType').find('option').eq(0).attr('selected', true);
       $('#recordType').find('option').eq(0).attr('selected', true);
       $('#department').find('option').eq(0).attr('selected', true);
       $('#bookMemo').val("");
         }
  });
  
     $('#my-prompt').modal({
       relatedTarget: this,
       onConfirm: function(e) {
        $("#my-modal-loading").modal("open");
        memoAdd = $('#ontimeType').val()+","+$('#handoutsType').val()+","+$('#recordType').val()+","+$('#department').val()+","+$('#bookMemo').val();
          $.post(
        '<?php echo __WEB_BASE_PATH__?>/include/control/updateBookRoom.php',
        {
             'id':addMemoBookid,
             'cmd':'updateManagerMemo',
             'memo':memoAdd
        },
        function(data) {
         $("#my-modal-loading").modal("close");
         initRoomSelect(initOption,initPage);
        }
   );
       }
    });

**Comment by haima95** [comment]
![image](https://user-images.githubusercontent.com/2991141/33157339-655a1e0e-d03c-11e7-8118-950acfbd9df1.png)

**Comment by haima95** [comment]
![image](https://user-images.githubusercontent.com/2991141/33157355-7bc997be-d03c-11e7-86ba-59882c970f3d.png)

**Comment by lwxyfer** [comment]
手动重置即可。
