### ISSUE TITLE
Bug: "react": "^16.2.0",轮播图组件无法使用

### ISSUE THREAD

**Issue by melorzhang** [amazeui/amazeui#1009]
**问题描述**

var CollapseMixin = {
  propTypes: {
    defaultExpanded: _react2.default.PropTypes.bool,
    expanded: _react2.default.PropTypes.bool
  },
ProTypes为空，PropTypes.bool报错，
react15.x把PropTypes移除了，
估计是依赖没更新，就报错了。
没上生产。按照复现步骤走就行。
还有步“骤”错了

**产生环境**

- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. react版本16，webpack构建，
2. 按照文档加入轮播图编译后就不能运行了
...

**Comment by minwe** [comment]
React 16 中把 PropTypes 单独拆出去了，需要把引用 React.PropTypes 中的地方都改一下。

**Comment by melorzhang** [comment]
我知道啊。。我是建议维护团队去更新这个依赖啊，下载的人自己去更新依赖是可以，但是这不是合适的解决方案啊

**Comment by minwe** [comment]
你用的是 amazeui-react？明天我看看能不能处理一下

**Comment by melorzhang** [comment]
amazeui-touch

**Comment by minwe** [comment]
Resolved via https://github.com/amazeui/amazeui-touch/commit/2957fc6967d50091fe10bec3abad3f03dd61b422
