### ISSUE TITLE
使用ScrollSpy滚动侦测插件遇到的问题

### ISSUE THREAD

**Issue by xjtarzan** [amazeui/amazeui#1014]
## 问题描述

在使用 ScrollSpy 这个滚动侦测插件时候，无论是往下滚还是往上滚都会触发动画效果。

能否只让动画触发一次呢？ 就是说只在第一次进入的时候动一次，之后就不会再动了，除非刷新页面。

## 产生环境

- **设备及型号：** 联想笔记本电脑
- **操作系统及版本：** windows 10
- **浏览器及版本：** 360浏览器12

**Comment by lwxyfer** [comment]
```
{repeat: false}
```
