### ISSUE TITLE
文件选择域，点按钮旁边空白的地方也能触发

### ISSUE THREAD

**Issue by lvjiaxuan** [amazeui/amazeui#1020]
## 文件选择域，点按钮旁边空白的地方也能触发

文件选择域，点按钮旁边空白的地方也能触发

## 产生环境

- **pc**（手机、平板等移动设备时填写此项，如 `iPhone 6s Plus`）
- **win7**（在系统设置关于里面可以查看）
- **chrome**（一般在浏览器「帮助」或者「关于」里面）
- **。。。**（请尽量提供可在线查看的演示地址）
- [**。。。**]([url](url))

## 复现步奏

1.
2.
...

**Comment by minwe** [comment]
```
.am-form-file input[type=file] {
    position: absolute;
    left: 0;
    top: 0;
    z-index: 1;
    width: 100%;
    opacity: 0;
    cursor: pointer;
    font-size: 50rem;
}
```

宽度改一下，改成跟按钮一样宽。

设置 `.am-form-file` 的宽度，或者设置 `disaplay: inline-block` 也可以。
