### ISSUE TITLE
Bug: js-datepicker选择后的值应该用什么方式清空？

### ISSUE THREAD

**Issue by DK-Coder** [amazeui/amazeui#1024]
**问题描述**

在使用js-datepicker的页面，我做了一个重置的按钮，按钮的效果是把input的value全部设置为空字符串，然后再点开日历控件，发现不显示日期了。但是在chrome的开发者工具中可以看到input的value属性有值。

**复现步奏**

1. 日历控件中选择其中一个日期
2. 调用$(".ims-input-calendar").val(""); 将input的值变为空字符串
3. 再打开日历选择控件，选择日期，发现页面上无法再显示选中的日期的值，但是在开发者工具中可以看到input的value属性有被选择的日期

![image](https://user-images.githubusercontent.com/13533447/35613903-4764d5e0-06a8-11e8-8c44-8ef84c52d78d.png)

**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

```
所以想问一下，正确的清空值，应该怎么清空？

**Comment by minwe** [comment]
```
$(".ims-input-calendar").attr('value', ''); 
```

这样可以。

**Comment by heshibin** [comment]
不行啊
`$(function(){
		$(".am-input-sm").change(function(){
			if($(this).val() == '') {
				$(this).attr('value', ''); 
			}
		});
	})`

**Comment by heshibin** [comment]
> ```js
> $ （“ .ims-input-calendar” ）。attr （'值' ， '' ）; 
> ```
> 
> 这样可以。

不行啊 救救孩子吧
`$(function(){ $(".am-input-sm").change(function(){ if($(this).val() == '') { $(this).attr('value', ''); } }); })`
