### ISSUE TITLE
垂直滚动右下角有拖动的三角

### ISSUE THREAD

**Issue by toknT** [amazeui/amazeui#1028]
## 问题描述

垂直滚动手机访问右下角有三角**看着像textarea的右下那个**
[文档地址](http://amazeui.org/css/utility#chui-zhi-gun-dong)

## 产生环境

- **浏览器及版本：vivalid 1.14.1077.55 其他浏览器开手机版也有截图是vivalid 这个浏览器里看着像个黑点** 

- **问题截图/录屏：**

![amazeui_am-scrollable-vertical_bug1](https://user-images.githubusercontent.com/15935037/37329928-c9f47c68-26e2-11e8-96da-a3b4642e667e.png)

**Comment by minwe** [comment]
```
.am-scrollable-vertical {
  resize: 'none';
}
```

自己加上这个。

**Comment by toknT** [comment]
@minwe 加了resize 可以,但希望框架里能直接有这个(我pr了)
