### ISSUE TITLE
Amaze UI项目的领导者、云适配CEO陈本峰

### ISSUE THREAD

**Issue by xiaochanglaoshi** [amazeui/amazeui#1060]
1. 这个是一个很好的开源项目,我感谢开源作者的贡献和付出
2. 今天看到红芯浏览器套个Chrome 浏览器就说是自主的项目，脸在哪里 
3. Amaze UI 的前世今生
在中关村创业大街旁边的办公室中,Amaze UI项目的领导者、云适配CEO陈本峰欣然接受了InfoQ中国总编辑崔康和高级编辑郭蕾的专访。陈本峰首先谈起了Amaze UI开源的背景,云适配是专注前端技术的公司,在把网站从电脑版转到手机版的时候,需要一个手机的前端框架。从创业初期开始积累,Amaze UI逐渐发展起来。

早期的时候,对这种移动端的Web界面框架比较少。国外的这块移动版做得相当的好,我觉得他们兼容性做得不错,但是速度非常慢,打开非常慢,所以无法忍受。于是我们当时决定自己做,所以就有了这套框架(Amaze UI),一直以来都是给云适配整套体系用的,后来我们觉得这套东西可以剥离出来,让别人也能用。所有人开发移动网站的时候,都应该需要这么一个框架,因为这样可以大幅度提高开发效率,不需要重新发明,这是一个基本的思想。
 [陈本峰：Amaze UI的开源之道](https://www.aliyun.com/jiaocheng/678120.html)

**Comment by smilefufu** [comment]
沙发，吃瓜围观

**Comment by Desmond-Liu** [comment]
手法拙劣的诈骗
