### ISSUE TITLE
承接国产浏览器打包服务

### ISSUE THREAD

**Issue by Desmond-Liu** [amazeui/amazeui#1061]
三包太不严谨了，我可以4、5、6 ...包， 价格好说，需要的话联系我

**Comment by Desmond-Liu** [comment]
看这个ui ，前端技术应该很不错， 为什么要用这么拙劣的手段骗钱？

**Comment by Andesome** [comment]
公平竞争，价格更优

**Comment by mablevi** [comment]
估计技术团队已经集体离职2年了

**Comment by EchoWht** [comment]
哎

**Comment by LiZheGuang** [comment]
这个框架用过 一般般

**Comment by oukohou** [comment]
![image](https://user-images.githubusercontent.com/16237619/44198372-d021ff00-a173-11e8-834b-b64d4e895d20.png)

**Comment by EtherDream** [comment]
![1](https://user-images.githubusercontent.com/1072787/44201714-8be72c80-a17c-11e8-9cf9-bbc777a21fd1.jpg)

**Comment by lwxyfer** [comment]
无关话题
