### ISSUE TITLE
2.5亿给浏览器换个皮肤？

### ISSUE THREAD

**Issue by qwertyuiop6** [amazeui/amazeui#1066]
这个项目技术负责也跑路2年了吧，该关了

**Comment by kumfo** [comment]
估计是的吧，本身amazeui还算是可以的，但是现在好害怕是抄袭的。

**Comment by oiuv** [comment]
不用怕，本来就是抄袭，amazeui就是bootstrap框架改的，你怕个P。

**Comment by yanue** [comment]
哪里是抄袭,是站在巨人的肩膀上 ^_^

**Comment by lwxyfer** [comment]
1. 浏览器是浏览器，amazeui 是 amazeui。
2. amazeui 使用的开源项目都明确在 README 和 代码注释中，如有违反协议请直接举报即可。
