### ISSUE TITLE
好像官网504了

### ISSUE THREAD

**Issue by Kratosmax** [amazeui/amazeui#1137]
## 问题描述

网站炸了

## 产生环境

- **演示地址：**
https://amazeui.clouddeep.cn
- **问题截图/录屏：**

![image](https://user-images.githubusercontent.com/26643694/70783356-9989e200-1dc3-11ea-9dbf-25f748aba558.png)

**Comment by minwe** [comment]
#1112 有镜像链接

**Comment by Kratosmax** [comment]
谢谢大佬回复
