### ISSUE TITLE
Please make English the default

### ISSUE THREAD

**Issue by dandv** [amazeui/amazeui#276]
http://blog.codinghorror.com/the-ugly-american-programmer/

**Comment by hiwjcn** [comment]
there will be a chinease version for chinease and english version for global.....
but i do not think  english version will be a default...you can check the slogan of amazeui....

by the way zui is also a amaze ui, just like http://www.zui.sexy/docs/javascript.html#messager

best regards to you

**Comment by minwe** [comment]
Over the short-term, we couldn't make English the default.

Instead, we offer docs in English:  http://amazeui.github.io/docs/en/.

Most of Amaze UI users are  in China, and their English is pool. 

Thank you for your attention.

**Comment by minwe** [comment]
@dandv 

I don't think so.

Most of those are `coding farmer`, not real programmer / developer.

They do not even know how to report a clear, meaningful issue in Chinese.

Learning English is very difficult to them, some of them are lazy and want others tell them anything.

This is one reason why there already Bootstrap, Foundation but we still create Amaze UI. We have to use Chinese, we are in China and facing those user.

I know English a very important skill to non-English speaking country. I certainly hope more and more Chinese developer learning English and making  more contribution to open-source community.

**Comment by jslegers** [comment]
Of course, most of Amaze UI users are in China. There was no English documentation until a few weeks ago. And now there actually are English docs, they're still pretty hard to find.

The English version of the documentation should be available from [amazeui.org](http://amazeui.org/) through a "language selection" button. That would make the framework's docs a lot more accessible for an international public and could draw in a whole new audience.
