### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by Codewyvern** [amazeui/amazeui#306]
The amazeui is beautiful!
I want to start using it but I don't speak Chinese.
Do you think eventually there will be a translation?

**Comment by joni2back** [comment]
+1 it is a waste

**Comment by hufuxin011** [comment]
start studying

**Comment by minwe** [comment]
Amaze UI docs English translation is online now: http://amazeui.github.io/docs/en/

Big thanks to @hongdp.

**Comment by jslegers** [comment]
:+1:
