### ISSUE TITLE
Bug: data-am-popover 模态窗口下会被遮挡

### ISSUE THREAD

**Issue by jxwy001** [amazeui/amazeui#398]
**问题描述**  模态窗口里有个按钮 
                        data-am-popover="{content: '鄙是点击 Hover 显示的 Popover', trigger: 'hover focus'}" 

这样 提示的信息会被模态窗口遮挡 看不见   修改了am-popover z-index也不行

（描述一下问题）

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; rv:34.0) Gecko/20100101 Firefox/34.0
```

**Comment by minwe** [comment]
使用 v2.6.0，加上：

```css
.am-popover {
  z-index: 1150;
}
```

解决问题。
