### ISSUE TITLE
Bug: 单张图片组件和select下拉在ipad中同时使用，select下拉在打开时，会同时出现单张图片的黑色背景

### ISSUE THREAD

**Issue by HeChangGG** [amazeui/amazeui#460]
**问题描述**
单张图片组件和select下拉在ipad中同时使用，select下拉在打开时，会同时出现单张图片的黑色背景
（描述一下问题）

**产生环境**
ipad
- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：ipad 8.1
- 浏览器及版本：safari
- 演示地址：

**复现步奏**

1. 同时使用单张图片和select，点击选择select，会显示出单张图片的背景
2. select的位置高度超过ipad竖屏时
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; rv:36.0) Gecko/20100101 Firefox/36.0
```

**Comment by Minwe** [comment]
有可以直接查看的演示页面吗？

**Comment by minwe** [comment]
无后续反馈，视为已经解决，作关闭处理。
