### ISSUE TITLE
妹子的后台模板能不能更加完善些

### ISSUE THREAD

**Issue by luisedware** [amazeui/amazeui#523]
就是想使用妹子做一款cms，但感觉后台模板似乎不够完善。顶部导航条和左侧菜单栏能否改成随滚动条滚动固定在上方和左方 :)

**Comment by Minwe** [comment]
短期内没有时间处理这个。
如果有的话，可以提供一些 BootStrap 之类的做的后台模板，我们移植一下。

**Comment by AnnEsaon** [comment]
我可以提供后台模板，请问你的邮箱是多少，找了一下，找不到，用github时间不多:D

**Comment by Minwe** [comment]
minwe@yunshipei.com，谢谢。

**Comment by Minwe** [comment]
模板收到，谢谢。我们要一个月以后才能模板相关转换工作，请关注。

**Comment by Teddy-Zhu** [comment]
@Minwe 后台模版的话 有很多，可以参考下这样的，比较综合，旨在把所有的Amaze Uide控件用上去
url: http://www.zi-han.net/theme/hplus/

**Comment by huazi221** [comment]
用ace吧，那个做的挺好看

**Comment by Yeocat** [comment]
最近是要推出结合React.js的Amaze UI后台模板吗？时间过去已经一个月多了，期待独立mobile版的Amaze UI,继续密切关注

**Comment by Minwe** [comment]
会有 React 版的管理后台模板。

jQuery 版的也加上了固定顶部和边栏的模板：
https://github.com/allmobilize/amazeui/blob/master/docs/examples/admin-index-fixed.html
https://github.com/allmobilize/amazeui/blob/master/docs/examples/assets/css/admin.css

**Comment by Yeocat** [comment]
期待React版的管理后台模板，公司内部用的系统已使用上amaze ui jQuery版，反映不错。
等React版的管理后台模板出来之后，准备重构公司项目，加个油勒~~

**Comment by appleboy** [comment]
@Minwe 期待 React 管理後台模板

**Comment by Minwe** [comment]
http://www.zi-han.net/theme/hplus/ 基本上就是 http://diliat.in/themeforest/sentir/1.3.0/index.html http://themeforest.net/item/sentir-responsive-admin-and-dashboard-ui-kits/7700260 的翻版

里面用到的一些插件已经整理到 https://github.com/allmobilize/amazeui/wiki/Web-%E9%A1%B5%E9%9D%A2%E5%BC%80%E5%8F%91%E4%BC%98%E7%A7%80%E8%B5%84%E6%BA%90%E6%95%B4%E7%90%86

**Comment by LuisEdware** [comment]
@minwe 基于React.js的管理後台模板什么时候出？

**Comment by minwe** [comment]
后台模板整体布局在 [2.6.0](https://github.com/amazeui/amazeui/releases/tag/v2.6.0) 中做了调整，更符合后台布局管理。

至于上面评论提到的第三方插件，有需要的可以自行下载使用，不再做整合示例。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://przystanekprl.pl/inform.php?gt>

 

Again_moon@sohu.com
