### ISSUE TITLE
Bug: 在侧边栏展开项目时文字图标出现抖动现象

### ISSUE THREAD

**Issue by noe132** [amazeui/amazeui#684]
**问题描述**

在admin-index.html页面下点击左侧侧边栏的可展开项目， 展开项目的时候文字图标出现抖动现象

**产生环境**
- 设备：台式机 CPU:xeon E3 1230v2 GPU:GTX760
- 操作系统及版本：Windows 8.1
- 浏览器及版本：Firefox 39
- 演示地址：http://amazeui.org/examples/admin-index.html

**复现步奏**
1. 点击左侧页面模块，此时会展开二级菜单
2. 在动画过程中，整个侧边栏的字会出现轻微抖动

gif动画演示地址:
http://noe132.com/blog/wp-content/manual_upload/amazeui_bug.gif

ps:
其他浏览器(chrome ie)无此问题
只测试过win平台
硬件加速无关系，开启关闭都有问题
我用的N卡，我同学的A卡都有次问题，目测应该是firefox的bug
但是如果使用JQ的slideToggle来控制ul元素的显示则不会出现抖动
**UA:** 

```
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
```

**Comment by minwe** [comment]
可能是 FF 的问题，或者是 FontAwesome 的问题 FortAwesome/Font-Awesome#671

留到 Firefox 40 正式版发布以后再来看一下这个问题。

**Comment by minwe** [comment]
Firefox 40 中仍然存在这个问题，不过出现的频率低一些。

**Comment by noe132** [comment]
closing it due to lack of response
