### ISSUE TITLE
Modal 交互窗口能去掉后面的遮罩层吗？

### ISSUE THREAD

**Issue by MetSystem** [amazeui/amazeui#689]
@minwe 在吗？
妹子缺少提示组件，Modal 交互窗口有遮罩导致提示时会一闪，体验不友好。
是否可以添加一个属性去掉遮罩层。这样Modal也可以用消息提示。

**Comment by xfworld** [comment]
顶！请求@minwe支援  ^_^

**Comment by minwe** [comment]
回头看一下吧。

**Comment by MetSystem** [comment]
谢谢

**Comment by upzvit** [comment]
谢谢，有用

**Comment by xcchcaptain** [comment]
@minwe
使用data-api方式初始化的modal在关闭时会有一个黑色的底框延时关闭的现象，感觉体验不好，不知有无方法改善,官网的popup demo在火狐下可以看到效果，其他浏览器未测试
目前采用js的方式没有出现类似的情况

**Comment by tubephp** [comment]
可不可以添加指定模态框遮罩的父容器

**Comment by TianYiGG** [comment]
上班打卡
