### ISSUE TITLE
Bug: panel和Selected组合使用时Selected的下拉弹出框被panel遮住。

### ISSUE THREAD

**Issue by kennter** [amazeui/amazeui#699]
**问题描述**

Bug: panel和Selected组合使用时Selected的下拉弹出框被panel遮住，初步判断是z-index的原因。

**产生环境**

- 操作系统及版本：win7
- 浏览器及版本：chrome版本 44.0.2403.107 m (64-bit)
- 演示地址：
  Amazeui下载包中的admin-form.html页面。

**截图**
http://www.116t.com/amazeui-bug.png
直接上传报错。

**Comment by kennter** [comment]
@minwe 
没人理我，如果问题描述有问题请给个回应啊。

**Comment by minwe** [comment]
看到这个问题，回头处理一下。

**Comment by kennter** [comment]
@minwe 
是因为.am-tabs-bd这个class的overflow问题。
我现在暂时的处理方式是这个这个class加上了。
    overflow:visible;
    display:-webkit-box;

**Comment by minwe** [comment]
好的，谢谢。你先这样处理吧。
我得看看调整以后会不会对动画产生影响，然后决定用什么方式修复。

**Comment by minwe** [comment]
加上 `overflow:visible` 后，tab 切换时会溢出显示在外面，不太雅观。

折衷方案，加了一个 `.am-tabs-bd-ofv` 的 class，有需要时加在 `.am-tabs-bd` 上。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://biltema24.ru/odd.php?b0ilv>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://fortunaplus.net/actress.php?ck2ih>

 

Again_moon@sohu.com
