### ISSUE TITLE
Bug: 表单验证与日期插件结合使用问题

### ISSUE THREAD

**Issue by dzcms** [amazeui/amazeui#711]
**问题描述**

表单验证，日期插件，选完日期  仍提示为空   需要再重新选一次

**产生环境**

- 设备：手机
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**Comment by dzcms** [comment]
怎么解决？

**Comment by minwe** [comment]
还没来得及细看，你试一下选择日期以后触发一下日期输入框的 `change` 事件。

**Comment by myfancy** [comment]
这个改动会导致：JS插件 | 日期组件 | 1.6 自定义事件 无法执行，直接报错。
报错内容：Uncaught TypeError: Cannot read property 'trigger' of undefined
我尝试着将你新增的 $input.trigger('change'); 模仿上面的写法修改为：
this.$element.trigger({
	type:'changeDate.datepicker.amui',
	date:this.date
});
发现正常了，请检查一下这里到底该怎么处理，因为没有仔细看过咱们的源码。

**Comment by haima95** [comment]
@minwe 求教个问题，怎么设置一个datepicker进行minviewmode切换，在月视图和日视图间切换。好像$().datepicker(format)只能设置一次，再调用时没效果

**Comment by minwe** [comment]
@haima95 什么场景需要切换一个输入框的视图？

**Comment by zhouzane** [comment]
12321321
