### ISSUE TITLE
validator 增加 destroy API

### ISSUE THREAD

**Issue by targetare** [amazeui/amazeui#719]
AJAX提交表单后，如果想重复使用此表单（比如能多次提交），可以通过 $('form').trigger('reset') 来重置整个表单，但是表单验证这方面如何 reset ?

**Comment by minwe** [comment]
没有 reset 的 API，可以通过以下方式销毁 validator 实例：

```js
 $('#your-form').validator('removeMark').removeData('amui.validator');
```

需要的时候再通过 ` $('#your-form').validator()` 方式重新初始化就行。

后续会添加一个销毁实例的 API。

**Comment by targetare** [comment]
'''
// 3. form validator reset
            $form.find('.am-form-success, .am-form-error, .am-field-error, .am-field-valid')
                 .removeClass('am-form-success am-form-error am-field-error am-field-valid');
            /*
             * 参考源码 : 
             * (1). Validator.prototype.init -> $element.data('amui.checked')
             * (2). Validator.prototype.validateForm
             * (3). Validator.prototype.isValid
             */
            $form.data('amui.checked', false);
            // console.dir($form.find(validator.options.allFields))
            $form.find(validator.options.allFields).data('validity', null).data('amui.dfdValidity', null);
'''
我目前这么做的.
