### ISSUE TITLE
jqgrid

### ISSUE THREAD

**Issue by xfworld** [amazeui/amazeui#735]
@minwe 为嘛要选datatable为表格组件，不选jqgird的呢？ 同是mit许可，觉得jqgrid比datatable好一点，可能是我感官上的 ：）
至少，我觉得jqgrid 相关的API和文档更加丰富

http://www.soliman.nl/test/jqgrid.bootstrap/jqGrid.bootstrap.html#

这个是bootstrap的例子...

**Comment by minwe** [comment]
这个太丑了吧，类似的功能 DataTable 都有。

**Comment by xfworld** [comment]
哈哈，我后来看了下还是官方的例子比较漂亮；
关键是dataTable 实例化后，在移动端貌似效果不太好；特别是滑动table的时候，感觉有点问题；
可能是我没找到窍门，我在看看吧；
下面是官方的例子和中文的文档
http://www.guriddo.net/demo/bootstrap/
http://blog.mn886.net/jqGrid/

**Comment by minwe** [comment]
https://github.com/amazeui/jqgrid  

抛砖引玉，还需进一步调整测试。
