### ISSUE TITLE
[Bug] 2.4.2版本，按钮交互js组件中的单选框组件逻辑存在浏览器兼容性问题

### ISSUE THREAD

**Issue by SilentTiger** [amazeui/amazeui#747]
FF 41.0 下面，单选框 最外层的div容器，如果设置尺寸样式为 am-btn-group-xs，而不是示例中的am-btn-group，则里面的按钮交互逻辑会变成复选框的逻辑！

**Comment by SilentTiger** [comment]
我又发现，未压缩版的js里面没有这个问题，而页面引用压缩过的 amazeui.min.js 之后才会有这个问题...囧..

**Comment by minwe** [comment]
:anguished:  可能是不同的 JS 引擎对压缩的后的代码解析有一些差异，回头检查一下。

**Comment by alwayrun** [comment]
可以用不同的压缩方式看看。

**Comment by bshy522** [comment]
可能是分号什么的 的原因.

**Comment by minwe** [comment]
http://bin.amazeui.org/quqone/edit?html,console,output

我测试了一下没发现你说的这个问题。

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:41.0) Gecko/20100101 Firefox/41.0

FF 版本是 `41.0.2`。

**Comment by minwe** [comment]
问题无法复现，可能是浏览器本身的 bug 已经修复。

先关闭了，如果再遇到可以重新打开。
