### ISSUE TITLE
select组件在单选时能否不自动选择第一个选项

### ISSUE THREAD

**Issue by ucando** [amazeui/amazeui#749]
现在的select组件总会自动将第一个选项默认选中，无论你有没有加“selected”选项

**Comment by minwe** [comment]
默认选中第一个是 HTML 规范中 `<select>` 元素的默认行为，当时这么处理也是和规范统一。

回头看看能不能加个选项吧。

**Comment by shaohao2014** [comment]
把第一个选项改成：<option value=""></option>即可

**Comment by ucando** [comment]
如果第一个选项改成```<option value=""></option>```，会生成一个空白的选项

**Comment by keyiL** [comment]
怎么设置不隐藏value=""的选项，我们的业务逻辑里边value=""是全选的意思

**Comment by piglingcn** [comment]
我写了个<option value="">全部</option>怎么没了，这个有用的呀

**Comment by piglingcn** [comment]
新增的“v2.5 增加了这个功能，只需将第一项设置为空的 <option> 即可”，这个功能真SB，原来写的< option value="" >全部< option > 都不显示了。搞到组件都要找别的来替代。

**Comment by piglingcn** [comment]
“v2.5 增加了这个功能，只需将第一项设置为空的 即可”

说真的，这个功能真SB，还不如不加，原来写的< option value="" >全部< option > 都不显示了。搞到组件都要找别的来替代。

**Comment by piglingcn** [comment]
有用户提出默认不选中第一项的需求，v2.5 增加了这个功能，只需将第一项设置为空的 <option> 即可。
哪 个SB用户提出的！！！！站出来，不打死你

**Comment by Aeloth** [comment]
那个傻子提的啊，这value="" 是全选，很令人蛋疼

**Comment by veryhard2k** [comment]
搞毛啊，为什么把第一项 value="" 给隐藏啊。 
value=“” 可以作为不选 或者说是全部的意思。
这么一弄，用户万一随便选了一个，都没办法取消。逻辑上就错了。
