### ISSUE TITLE
ajax 取回的dom ， 插入后 amazeUI的事件都失效了

### ISSUE THREAD

**Issue by ving0099** [amazeui/amazeui#762]
ajax 取回的dom ， 插入后， amazeUI事件都失效了，请问要如何绑定amazeUI的事件？

**Comment by alwayrun** [comment]
@ving0099 是取回后的DOM上有一些事件失效还是导致之前的DOM事件失效

**Comment by xfworld** [comment]
先off 取消事件绑定，然后在进行on绑定
比如：('#xxx').off('click').on('click',function(){ alert(aa);});

**Comment by minwe** [comment]
https://github.com/allmobilize/amazeui/issues/480#issuecomment-84927084

> AMUI 则是在 Ready 事件里面初始化默认接口，动态插入的 DOM 已经是在 Ready 事件之后，所以没有绑定相关事件。

> 一些插件中通过事件委托可以解决动态插入 DOM 的事件绑定问题，但是并不是所有插件都可以这样，因为有的插件用户操作没有定位到要绑定元素的 DOM 上。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://xn--b1adejdnuhp.xn--p1ai/lack.php?zpx7m>

 

Again_moon@sohu.com
