### ISSUE TITLE
为什么Figure 单张图片第一次打开图片变形第二次就好了

### ISSUE THREAD

**Issue by yuechen323** [amazeui/amazeui#765]
我就是copy官网的代码，以下这段是用js动态插入进去的，其中src和data-rel是图片地址或base64的dataurl

```html
<figure data-am-widget="figure" class="am am-figure am-figure-default" data-am-figure="{  pureview: 'true' }"><img src="" data-rel=""/></figure>
```

现象：
1. 动态插入后，等了大概1分钟才可以点击看大图，就是鼠标移动到图片上没有变成小手，也无法点击，1分钟后可以
2. 点击后看大图都变形了，然后关闭后再打开回复正常

**Comment by minwe** [comment]
参考 https://github.com/allmobilize/amazeui/issues/356

插入以后执行：

```js
AMUI.figure.init();
```

**Comment by yuechen323** [comment]
加了这句AMUI.figure.init();现象1解决了，图片可以立即点击，但是现象2还存在，第一次点击图片比例不对，第二次正常

**Comment by minwe** [comment]
比例不对应该是浏览器的渲染机制有问题，我没喷到过。

**Comment by minwe** [comment]
没有后续反馈，暂时关闭。
