### ISSUE TITLE
model在ios遮盖层会穿透

### ISSUE THREAD

**Issue by wilyh** [amazeui/amazeui#767]
model在ios遮盖层会穿透，能点击到遮盖到链接@minwe，请大神帮忙

**Comment by minwe** [comment]
**问题描述**

（描述一下问题）

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1.
2.
...

**Comment by wilyh** [comment]
问题描述

modal在ios遮盖层会穿透，能点击到遮盖到链接，安卓的不会@minwe

产生环境

设备：iphone
操作系统及版本：ios 8&ios9
浏览器及版本：
演示地址：http://pymxl.pagekite.me/fmps/plug-in/huodong/dobule11/index.html
复现步奏

1.访问链接后，点击屏幕遮盖层底下的图片<a>

...

**Comment by minwe** [comment]
你是说在 Modal 上滑动的时候下面的内容会滚动？

**Comment by wilyh** [comment]
@minwe 不是，modal 弹出后，在ios下，遮盖层被穿透了，遮盖层下面的链接还是会被触发，我给的链接地址，你可以试一下，就点弹出框下面的那三个图就可以

**Comment by minwe** [comment]
我 QQ 和 Safari 打开都点不到。

**Comment by wilyh** [comment]
微信里访问，我是在微信里访问碰到的

**Comment by minwe** [comment]
你浏览器里写上微信不就不用浪费时间再问答了嘛。

我 iOS 9.2 没有这个问题，你可以试一下阻止 modal 上的点击事件冒泡。

**Comment by wilyh** [comment]
额，阻止modal的点击事件冒泡，这个要怎么弄？
我的也是ios9.2啊，点最下面的位置

**Comment by minwe** [comment]
```js
$(document).on('click', '.am-modal, .am-dimmer', function(e) {
  e.stopPropagation();
});
```

整个屏幕点遍了也没有你说的问题。

**Comment by wilyh** [comment]
不能贴图，不然我可以截图给你。访问进去，左下角不是有个室内清洗的图片吗？点一下。我的是5s，可能你的不是。我试试你给的语句，谢谢

**Comment by minwe** [comment]
点了，点不到，你试试吧。

<img width="514" alt="2015-11-06 3 52 25" src="https://cloud.githubusercontent.com/assets/4370770/10992172/6df5ee30-849e-11e5-82e6-48bdf28af039.png">

点 selecting them 可以传图。

**Comment by wilyh** [comment]
![qq 20151106155706](https://cloud.githubusercontent.com/assets/15682035/10992270/5e729bb0-849f-11e5-9530-237211a0733c.png)

**Comment by wilyh** [comment]
![qq 20151106160942](https://cloud.githubusercontent.com/assets/15682035/10992482/2efb871e-84a1-11e5-9e08-c6a71aa27b46.jpg)

**Comment by minwe** [comment]
我刚才都点过了，点不到的。

**Comment by wilyh** [comment]
难道还跟苹果手机有关，我这边5s就有问题

**Comment by wilyh** [comment]
我拿了好几台苹果手机，4s,5,5s都出现穿透了

**Comment by minwe** [comment]
有可能吧。

你加上那个代码也不起作用？

**Comment by wilyh** [comment]
恩，代码加上也不行

**Comment by minwe** [comment]
一般用户也不会点到下面去吧。

如果你实在想处理，那就阻止掉 modal 打开时候点击到图标上的事件。

```js
$('.icons').on('click', function(e) {
  if ($('#modal').is('.am-modal-active')) {
    e.preventDefault();
  }
});
// .icons 和 #modal 改为响应的选择符
```

**Comment by wilyh** [comment]
好的，非常感谢

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://dierenplek.nl/tank.php?6d5>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://ednaferman.com.au/tremendous.php?4>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://kattennaam.nl/content.php?5>

 

Again_moon@sohu.com
