### ISSUE TITLE
希望更新staticfile的版本和添加到百度公共库！

### ISSUE THREAD

**Issue by moye26** [amazeui/amazeui#769]
希望更新staticfile的版本和添加到百度公共库！谢谢！

**Comment by minwe** [comment]
我们提供的 CDN 也是使用的七牛的，和 staticfile 一样：

http://amazeui.org/getting-started#shi-yong-cdn

百度公共库回头看一下。

**Comment by moye26** [comment]
非常感谢~

**Comment by minwe** [comment]
https://cdnjs.com/libraries/amazeui

看了一下，CDNJS 中 Amaze UI 是同步更新的。

staticfile 和百度公共库都标榜同步 CDNJS，但都没有同步过来。

我已经在各自的的项目主页是反馈。

**Comment by minwe** [comment]
鉴于两个库都疏于维护，如果真正做到同步的 CDNJS 的时，问题自然解决。

已经做过相关反馈，但貌似无人问津。我们就不再浪费精力单独提交了。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://thverspaget.nl/hat.php?d>

 

Again_moon@sohu.com
