### ISSUE TITLE
表单自定义验证看了文档也不太清楚具体如何实现

### ISSUE THREAD

**Issue by mqliutie** [amazeui/amazeui#771]
```JavaScript
$('#your-form').validator({
  validate: function(validity) {
    // 什么时候会触发这个方法?
  }
})
```

**Comment by minwe** [comment]
默认参数：

```
 // 下列元素触发以下事件时会调用验证程序
  keyboardFields: ':input:not(:button, :disabled,.am-novalidate)',
  keyboardEvents: 'focusout, change', // keyup, focusin
```

以上事件都会触发 `validate()` 方法。

所以 `validate()` 里面要判断是不是你想验证的域，具体可以看一下文档里自定义验证的演示。

**Comment by mqliutie** [comment]
恩呢,知道了,已经测试成功了

**Comment by mqliutie** [comment]
不过有个问题,我在一个html内部测试的时候是可以的,用在angular里面就出问题了,只有focusout时候触发了事件,change,keyup, focusin都没起作用- -

**Comment by minwe** [comment]
Angular 的事件应该是另外一套机制，我几乎没用过所以不熟悉。

不过可以肯定的是，jQuery 插件直接用在 angular 里肯定是行不通的，不然 Bootstrap 就没必要再写一个 angular 版了。

**Comment by minwe** [comment]
你可以尝试在 Angular 把表单渲染完成以后，再初始化 jQuery 插件：

```js
$('#your-form').validate({
  validate: ...
});
```

这个顺序非常重要。
