### ISSUE TITLE
am-nav的水平导航am-nav-pills如果加上宽度自适应am-nav-justify在IE9下出错

### ISSUE THREAD

**Issue by oiuv** [amazeui/amazeui#775]
经测试，水平导航在IE9以下版本中如果加上am-nav-justify后，每个li都变成宽度100%的，然后……成居中的垂直导航效果了。

**Comment by minwe** [comment]
请说明白问题及 IE 版本。

**Comment by minwe** [comment]
![2015-11-24 11 34 51](https://cloud.githubusercontent.com/assets/4370770/11357133/754fd4e8-929f-11e5-85af-1a202454d267.png)
![2015-11-24 11 14 17](https://cloud.githubusercontent.com/assets/4370770/11357134/755396dc-929f-11e5-9e8f-fe5dff8b267a.png)

不要使用 IETester 之类的测试，不准确，高版本 IE 的兼容模式同样不准确。

**Comment by oiuv** [comment]
非IETester，是实际网页中的问题。

**Comment by minwe** [comment]
HTML 头按此

```html
<!doctype html>
<!--[if lte IE 7 ]><html class="no-js ie lte7 lte8 lte9 "><![endif]--><!--[if IE 8 ]><html class="no-js ie ie8 lte8 lte9 "><![endif]--><!--[if IE 9 ]><html class="no-js ie ie9 lte9 "><![endif]--><!--[if (gt IE 9)|!(IE)]><!--><html class="no-js"><!--<![endif]-->
```

**Comment by oiuv** [comment]
原来如此，知道了，搞定了，谢谢。
