### ISSUE TITLE
Bug: Selected组件和jquery form冲突的问题

### ISSUE THREAD

**Issue by kreocn** [amazeui/amazeui#781]
当引入jquery form时 selected Data API(<select data-am-selected>)组件无效
然后试用文档中写的 $('select').selectIt(options)
提示无此方法,我看了一下源码,发现selectIt,已经被注释掉了.

**Comment by kreocn** [comment]
浏览器 Chrome

**Comment by kreocn** [comment]
...我把jquery.form,放在amazeui.js的上面,就没有冲突了.........直接用$.fn.selected()就能重新加载.,但是我jquery.from的selected就不能用了
为什么取消了selectIt?建议直接试用selecIt,取消冲突

**Comment by minwe** [comment]
更新的时候把 `$.fn.selectIt` 删了。

你可以注册一个先用着：

```js
AMUI.plugin('selectIt', AMUI.selected);
```

我们再看一下怎么处理。

**Comment by minwe** [comment]
这样用吧：

1. jquery.form.js 放在 Amaze UI 的 JS 前面；
2. 让渡 `$.fn.selected`

  ```js
  // 恢复 jQuery Form 插件的 $.fn.selected，并把 Amaze UI selected 重新赋值给 $.fn.amSelected
  $.fn.amSelected = $.fn.selected.noConflict();        
  
  // 使用 Amaze UI 的 selected
  $('[data-am-selected]').amSelected();
 ```
