### ISSUE TITLE
关于validator

### ISSUE THREAD

**Issue by woxinqidai** [amazeui/amazeui#785]
row : 9234
 } else if (pattern && !re.test(value) && value) { // check pattern
    validity.valid = false;
    validity.patternMismatch = true;
  }

这一行, 这里所有通过正则校验的字段都被设置成了 validity.patternMismatch, 个人认为将正则的名称设置为 true 会更好, 比如 js-pattern-email, 这里 validity.email = true, 这里便于下文的错误消息获取, 如果找不到 validationMessages[locals]['email'], 再使用 patternMismatch, 消息定义起来会更加灵活, 望采纳!

**Comment by minwe** [comment]
谢谢建议。

不过自定义错误提示完全可以通过其他方式实现：

- 比如在 input 上设置一个保存错误提示的属性，发生错误的时候去读取那个值；
- 自己定义一个对象，根据 `js-pattern-xxx` 类名去读取相应的提示。

我们只提供核心功能，个性化的东西用户可以自行扩展定义。

**Comment by woxinqidai** [comment]
1) 在input上设置, 如果是通用的验证,比如email,mobile这种就很麻烦, 要每个地方都写
2) 不太明白你说的是什么办法

可以在这里判断下是否有 js-pattern-xxx, 有的话, 直接读取 js-pattern-xxx 的消息定义, 这样可以直接定义全局消息 js-pattern-email, js-pattern-mobile .... 使用上会方便许多
 row 9437
 if (message && Validator.ERROR_MAP[error]) {
    message = message.replace(placeholder,
      $field.attr(Validator.ERROR_MAP[error]) || '规定的');
  }

**Comment by woxinqidai** [comment]
哦, 明白你意思是自己去是先我上面说的代码.

**Comment by minwe** [comment]
显示错误提示目前没有内置在插件中，只是通过选项来提供接口。

通过 `validity.patternMismatch` 以及 `.js-pattern-xxx` 就可以知道是什么类型的数据错误，`validity.valid = false;` 这个属性就是多余的。

程序设计中这样的属性是不应该存在的。
