### ISSUE TITLE
Bug: android手机UI显示问题

### ISSUE THREAD

**Issue by welove312** [amazeui/amazeui#790]
**问题描述**
在小米3和小米4上打开官方组件，显示不出来，还有返回按钮显示不正常

**产生环境**
小米3、小米4上UI显示不正常
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
...

**Comment by minwe** [comment]
你说的官方组件是哪个页面里的？

小米有 n 个系统版本，上面还可以安装 n 中浏览器，请一一说明，并附上问题页面截图。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://emigratingtooz.com/than.php?bsx>

 

Again_moon@sohu.com
