### ISSUE TITLE
Amaze UI 在JSP使用中会导致图标排版出错

### ISSUE THREAD

**Issue by cnhj352** [amazeui/amazeui#794]
Amaze UI 在JSP使用中会导致图标排版出错，图标全部往上方移动，在html中正常

新增页面
2300        

成交订单
308

**Comment by cnhj352** [comment]
我截图传不上去，
cnhj352@vip.qq.com  可以邮我 发源码给你看看

**Comment by minwe** [comment]
JSP 传给服务器的也是 HTML，有问题可能是 jsp 输出的 HTML 代码解构不完整之类的。

看看浏览器控制台有没有报错。

**Comment by minwe** [comment]
长时间未提供 JSP 渲染结果。暂时关闭。
