### ISSUE TITLE
Bug: Selected组件，默认的onChange事件报错：this.state.value.split is not a function

### ISSUE THREAD

**Issue by openwings** [amazeui/amazeui#796]
**问题描述**

版本 1.0.0-beta2
68行，
当this.state.value = 2的时候，这个三元表达式会成立，于是调用了非[]数组的split方法，因此报错

**产生环境**

- 操作系统及版本：
Mac OS 10.x
- 浏览器及版本：
Chrome
- 演示地址：
无
**复现步奏**

1. Selected组件使用
2. 配置props和data（不要multiple，是单选）
3. 点击出现下拉后，选择，查看console，报错信息

**Comment by openwings** [comment]
补充：
data = [{
  value: 'all',
  label: '全部'
},{
  value: 1,
  label: '国家1'
}]

**Comment by minwe** [comment]
你说的是 React 版？

React 版应该发在这这边 https://github.com/amazeui/amazeui-react/issues

**Comment by openwings** [comment]
发错地方，官方链接应该区分一下。

**Comment by minwe** [comment]
你是从哪里点击来的？应该是地址有误，回头我们改一下。

**Comment by openwings** [comment]
http://amazeui.org/react
页面底部点击-》
http://amazeui.org/about/contact

-> issu

**Comment by minwe** [comment]
好，谢谢。
