### ISSUE TITLE
am-topbar-inverse导致错位

### ISSUE THREAD

**Issue by xiazhujie** [amazeui/amazeui#797]
amazeui2.5.0里的admin-user.html中，把导航条的am-topbar改为am-topbar-inverse，在小平幕上会导致页面错位的不亦乐乎，完全不能直视

**Comment by minwe** [comment]
有截图吗？
请按照  https://github.com/amazeui/amazeui/blob/master/CONTRIBUTING.md#bug-反馈 说明问题产生的环境。

**Comment by xiazhujie** [comment]
下载的amazeui2.5.0压缩包里把admin-user.html中第24行改为<header class="am-topbar-inverse admin-header">,用chrome模拟一下手机就能看到了,只是把am-topbar改为am-topbar-inverse.

**Comment by minwe** [comment]
你是把 `am-topbar` 改成 `am-topbar-inverse `，而不是在原来的基础上加上 `am-topbar-inverse ` （保留 `am-topbar`）？

**Comment by xiazhujie** [comment]
是我理解错了,惭愧
