### ISSUE TITLE
单选或多选的插件点击时控制台报错

### ISSUE THREAD

**Issue by zxw5775** [amazeui/amazeui#799]
选择时脚本报错 this.addClass is not a function

**Comment by minwe** [comment]
有演示地址吗？

**Comment by zxw5775** [comment]
@minwe 使用chrome在官网的单选多选插件页面点击看console就能看到

**Comment by minwe** [comment]
以后请说明是模拟触控模式，谢谢！

Resolved via e80ffa0a3a2f896925c61406e04607ac35a45082.
