### ISSUE TITLE
win7下执行npm install 出错

### ISSUE THREAD

**Issue by zhuzhengwen1983** [amazeui/amazeui#800]
我在win7 下 
node 4.2.3
npm 3.5.2

amazeui\amazeui-master   命令行中执行npm install 有警告
npm WARN optional Skipping failed optional dependency /webpack-stream/webpack/watchpack/chokidar/fsevents:

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

**Comment by minwe** [comment]
安装完成了吗？建议使用 npm `2.x`

**Comment by bshy522** [comment]
警告不影响.
fsevents这个包是用于mac下的.

**Comment by zhuzhengwen1983** [comment]
gulp appServer 可以启动
