### ISSUE TITLE
am-u-sm-push-**,am-u-sm-pull-**处理有问题，作用范围太大，不仅在小屏幕有效，大屏幕也有效

### ISSUE THREAD

**Issue by windsome** [amazeui/amazeui#801]
am-u-sm-pull-xx,am-u-sm-pull-xx作用范围为：
@media only screen
应该改为
@media only screen and (max-width:640px)

**Comment by minwe** [comment]
这就是所谓的**移动优先**。
当前主版本号下不会考虑做此调整。个人可以根据实际需要自己添加一些样式。

**Comment by windsome** [comment]
举个例子吧
<Col className="am-u-sm-pull-2 am-u-lg-push-2">2</Col>
在sm小屏幕下显示为左拉两个单位，但是在lg大屏幕下也显示为左拉两个单位，正常吗？
按正常理解，应该是在lg大屏幕下是右拉两个单位吧？这与移动优先没什么关系吧？

**Comment by minwe** [comment]
网格的设计理念文档里有说明，这里就不多说了。

 可以说一下要实现什么效果而无法实现的。如果需求比较特别，或者觉得官方的方式不合理，可以下载源码修改定制。
