### ISSUE TITLE
动态创建的下拉组件DropDown没有功能

### ISSUE THREAD

**Issue by leyou240** [amazeui/amazeui#802]
如题，动态创建DropDown之后，元素没有点击的效果和功能。并且导致页面重定向

**Comment by minwe** [comment]
https://github.com/amazeui/amazeui/issues/480#issuecomment-84927084

创建完了再调用相关玩法初始化组件：

```js
$('.xxx').dropdown();
```

**Comment by byadair** [comment]
var tmp= $(".am-dropdown")
    for(item of tmp){
        item.dropdown()
    }
提示dropdown is not a function()
