### ISSUE TITLE
关于调用JS插件 QRCode的建议

### ISSUE THREAD

**Issue by RemoveLove** [amazeui/amazeui#804]
建议在使用QRCode API调用的时候可以提供 image接口，让用户可以在二维码中间可以绘制头像。

**Comment by minwe** [comment]
这种个性化的功能不太考虑，前端做起来问题兼容问题比较多，后端做比较合适一些。

有相关需求又不想自己写的话可以直接使用 http://www.liantu.com/pingtai/ 这种服务。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://vecnushka.ru/role.php?bnoi>

 

Again_moon@sohu.com
