### ISSUE TITLE
Please don't recommend to block user zooming on mobile

### ISSUE THREAD

**Issue by dmitriz** [amazeui/amazeui#806]
These attributes to block user from zooming is a very hostile practice:

`<meta name="viewport" content="..., maximum-scale=1, user-scalable=no">`

It forces users with impaired vision into reading uncomfortable sized text or leaving the site for good.
It is especially harmful recommendation in a framework with many developers simply copying the files without thinking about the consequences.
If people need to zoom your site, they have a reason to do so and nothing can put them off more if they can't do it. No design is possible to accommodate everyone at the same time, and letting user to zoom is a very simple solution. Why blocking it is simply beyond my understanding. People will leave your site and you won't even know why!

**Comment by JerryDev** [comment]
I agree with you. I will translate your words to Chinese.

这些属性阻止用户缩放是一种非常敌对的做法。
<meta name="viewport" content="..., maximum-scale=1, user-scalable=no">
它迫使视力不好的用户以不舒服的文字尺寸来阅读，或者离开网站。
尤其有害的是在一个框架里被推荐这么做，而许多开发者只是简单的复制文本，并没有考虑这样做的后果是什么。
如果人们需要缩放你的网站。他们有理由这么做，没有什么能让他们更反感的了如果他们不能这么做的话。没有什么设计能同时适应所有人，让用户自己缩放是一个非常简单的解决方案。为啥阻止它简直超出了我的理解范围。人们可能离开你的网站而你甚至都不知道为什么！

**Comment by minwe** [comment]
Has removed `maximum-scale=1, user-scalable=no`, thanks.
