### ISSUE TITLE
Bug: Android中Slider无法使用

### ISSUE THREAD

**Issue by DarkMagicianTony** [amazeui/amazeui#812]
**问题描述**
Android中Slider无法使用，IOS中运行正常

**产生环境**
官方案例，我方调用Slider，Android环境中都无法正常运行

- 设备：（手机、平板等移动设备时填写此项） Android 三星NOTE2 7100
- 操作系统及版本：Android4.1.2
- 浏览器及版本：微信
- 演示地址：http://t.amazeui.org/?from=message&isappinstalled=0#/?_k=wocjpm中的Slider无法打开，我方的WebApp同样Slider无法正常运行

**复现步奏**

1. 打开http://t.amazeui.org/?from=message&isappinstalled=0#/?_k=wocjpm
2. 点击Slider
...

**Comment by minwe** [comment]
Move to amazeui/amazeui-touch#25.
