### ISSUE TITLE
Bug: NavBar 小屏幕无法折叠成更多按钮 

### ISSUE THREAD

**Issue by pcazheng** [amazeui/amazeui#813]
**问题描述**
NavBar 小屏幕无法折叠成更多按钮 
官网demo小屏幕可以折叠一下菜单成更多
为什么我下载下来复制代码运行不能折叠为更多按钮

**Comment by minwe** [comment]
可能原因：

- 菜单数量过少，组件设置的每个菜单最小宽度为 `120px`
- JS 没有正确执行

不贴实际的演示无法确定。

**Comment by minwe** [comment]
无后续反馈视为已经解决，作关闭处理。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://xn--b1adejdnuhp.xn--p1ai/beside.php?l>

 

Again_moon@sohu.com
