### ISSUE TITLE
生成tabs并open新的tabs时,会出现整体页面横移的情况

### ISSUE THREAD

**Issue by ningxzx** [amazeui/amazeui#814]

**Comment by ningxzx** [comment]
按照官网的方法,先给tabs的nav加一个li,然后给bd加一个panel.随后根据新增加的li,用open方法打开.参数是新增加的li的jquery对象.
在打开第二个第三个的情况下出现了偏移,
我已经在amazeui社区里提出了类似问题.里面附有图片

**Comment by ningxzx** [comment]
http://ask.amazeui.org/?/question/370
这是附有问题的链接,麻烦诸位了!

**Comment by ningxzx** [comment]
在新增加tabs时,还会出现点击nav无法切换tabs的现象,看了一下是因为this.transitioning 为false,我们项目用的是requirejs加载,框架是backbone,能否告知下可能的错误原因及解决办法.谢谢啦

**Comment by minwe** [comment]
滚动条问题参见 https://github.com/amazeui/amazeui/issues/807#issuecomment-167492541

**Comment by minwe** [comment]
动态插入 tab 参见文档中的演示代码，插入以后调用 `$tab.tabs('refresh');` 刷新 Tabs。

**Comment by minwe** [comment]
Resolved via 769a511,  see https://github.com/amazeui/amazeui/issues/807#issuecomment-167492541.
