### ISSUE TITLE
怎样全选checkbox？

### ISSUE THREAD

**Issue by shaohao2014** [amazeui/amazeui#818]
怎样全选checkbox？

**Comment by minwe** [comment]
https://www.baidu.com/s?wd=jquery%20%E5%85%A8%E9%80%89checkbox&rsv_spt=1&rsv_iqid=0x80d8f11700108a6f&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=0&rsv_t=7760lyNTLh92Kanm8cPEzkovcmO8Sw5ynlQw62SQ1ZA9gw4xaEWc4uRfNHc6%2BsR0P16Z&oq=%E6%80%8E%E6%A0%B7%E5%85%A8%E9%80%89checkbox&inputT=1111&rsv_pq=941a95cb00105899&rsv_sug3=8&rsv_sug1=1&rsv_sug2=0&rsv_sug7=100&rsv_sug4=1111
