### ISSUE TITLE
求思路。问题：选中下拉列表选项后出现相应表单选项。

### ISSUE THREAD

**Issue by shaohao2014** [amazeui/amazeui#819]
实现功能：当客户选中下拉列表中的选项后，原Form里出现相应的表单元素供客户填写。
给出思路就行，呵呵。
能给出demo最好，哈哈。

呵呵，参考了妹子的Selected插件demo后实现了，$selected.on('change', function() {}
第2个问题：选中项的不同，Form里出现的表单元素也不同，怎嘛实现？呵呵
答案：switch () {case "":....}

**Comment by shaohao2014** [comment]
呵呵，参考了妹子的Selected插件demo后实现了，$selected.on('change', function() {}

**Comment by xfworld** [comment]
恭喜，可以关闭了

**Comment by shaohao2014** [comment]
第2个问题：选中项的不同，Form里出现的表单元素也不同，怎嘛实现？呵呵
