### ISSUE TITLE
<input type=“radio”>里 不能用  data-validation-message=“”参数？

### ISSUE THREAD

**Issue by shaohao2014** [amazeui/amazeui#820]
`<input type=radio>`里边不能用 data-validation-message=“”参数？
我发现在里边设置data-validation-message=“请选择。。。”不管用。

**Comment by minwe** [comment]
授人以鱼不如授人以渔。

建议找本书 http://item.jd.com/11336695.html 先看看，理解代码如何工作，才能实现你想要的功能。

**Comment by shaohao2014** [comment]
好！我确实前端基础不足，我的前段学习路线是：所有问题先看源码，再根据源码学API，全部知识都是现查（jquery.com）的API文档，正如你说，经常卡克，效率超低。话说回来，amui真是很好用，对比之前用过arale、bootstrap，也染指过react.js，有点杂了。对于我这个php开发来说，amui很好上手，平时忙于工作与各种杂事，是得好好打打前端基础了，前端是个大杂烩，水也深，对于ES6也慢慢入门了，感谢amui。

**Comment by shaohao2014** [comment]
抱歉，再问个问题吧：验证插件里边，`$form.validator({ submit: function() {return false;} })`
reutrn false;提交不了Form，怎么submit表单呢？直接return?

**Comment by minwe** [comment]
验证成功 `return true` 就可以正常提交，没成功 `return false` 阻止提交。

**Comment by shaohao2014** [comment]
对基础知识有一个大概的了解以后，用的时候遇到问题，再回头去深入阅读理解，这样对你提高更有帮助。说得非常好！
