### ISSUE TITLE
模态窗口Actions数据过多问题

### ISSUE THREAD

**Issue by anjia0532** [amazeui/amazeui#821]
http://amazeui.org/javascript/modal#actions
如果数据过多，不能通过限制高度实现滑动获取数据。用户体验很不好。如下图
![qq 20160114162443](https://cloud.githubusercontent.com/assets/15098916/12319237/dbbe211c-badb-11e5-8d31-f4df53d5a9e4.png)
建议可以配置height，超长数据，可以上下滚动

**Comment by anjia0532** [comment]
如下图
![111111](https://cloud.githubusercontent.com/assets/15098916/12319607/68bec95c-bade-11e5-8c61-881558a0971b.png)

**Comment by minwe** [comment]
谢谢建议，回头看一下吧。

**Comment by minwe** [comment]
限制了 actions 的最大高度，至少不会溢出容器。

由于没有规定 HTML 结构，要实现截图中的效果需要自行根据自己的解构定制样式。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://arcomist.com/flash.php?t5eo>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://www.reach10.com/process.php?3st>

 

Again_moon@sohu.com
