### ISSUE TITLE
请求提供支持https的CDN

### ISSUE THREAD

**Issue by duruitang** [amazeui/amazeui#823]
现在大多数手机站、APP都需要https资源，请提供支持，感谢！类似 http://www.bootcdn.cn 一样最好。

**Comment by minwe** [comment]
https://cdnjs.com/libraries/amazeui

**Comment by duruitang** [comment]
用了，不是国内的，速度很慢...唉

**Comment by duruitang** [comment]
用了，不是国内的，速度很慢...唉

**Comment by minwe** [comment]
可以放在自己的存储空间上，七牛和又拍都支持 HTTPS。

**Comment by duruitang** [comment]
谢谢
