### ISSUE TITLE
Tab选项卡在导入jquery-ui的时候发生冲突

### ISSUE THREAD

**Issue by junliepigyao** [amazeui/amazeui#824]
版本：Amaze UI v2.3.0
          jQuery UI 1.11.4

问题描述：当前使用amaze Tab选项卡的时候，导入jqueryui会发生冲突导致Tab选项卡不能使用

**Comment by minwe** [comment]
参考

- https://github.com/amazeui/amazeui/issues/519#issuecomment-92175489
- https://github.com/amazeui/amazeui/issues/781#issuecomment-158873541

如果你要用 Amaze UI 的 Tabs，就把 Amaze UI 的脚本放在 jQuery UI 后面；否则，就放在前面。
