### ISSUE TITLE
怎么设置datepicker进行minviewmode切换，在月视图和日视图间切换

### ISSUE THREAD

**Issue by haima95** [amazeui/amazeui#827]
求教个问题，怎么设置一个datepicker进行minviewmode切换，在月视图和日视图间切换。好像$().datepicker(format)只能设置一次，再调用时没效果

**Comment by minwe** [comment]
回头我看一下吧。3

**Comment by minwe** [comment]
你这是要实现什么功能？能再具体说一下怎么交互的时候要切换。

**Comment by haima95** [comment]
不好意思，时间太久，我已经忘了当时想实现什么功能

**Comment by minwe** [comment]
好吧，那我先关了，以后遇到问题再提吧。抱歉没及时处理。
