### ISSUE TITLE
轮播图最外层有一条1px的灰色边框

### ISSUE THREAD

**Issue by Dachow** [amazeui/amazeui#828]
[实例](http://bin.amazeui.org/zozafasefe/edit?html,css,output)

slider头是
`<div class="am-slider am-slider-default" data-am-flexslider="{controlNav: false, directionNav: true, slideshow: true}" id="demo-slider-0">`

在css属性中没有找到这条边框，但是去掉am-slider-default，边框就没了，翻页箭头也没了。

**Comment by Dachow** [comment]
问题解决了，是am-slider层的box-shadow属性，设为0就可以了

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://meloni.com.tr/fun.php?n2np>

 

Again_moon@sohu.com
