### ISSUE TITLE
新建的modal怎么设置它不共用另一个modal的dimmer

### ISSUE THREAD

**Issue by haima95** [amazeui/amazeui#829]
@minwe  使用modal插件做弹出层的功能,如果在弹出层中再使用modal时,关闭的时候隐藏dimmer(所有的modal共用一个dimmer),所以我的问题时怎么在创建modal时指定不同的dimmer?

**Comment by SoyMeng** [comment]
在弹出层中使用modal是没问题的,就是关闭的时候需要注意。动画需要1秒钟的执行时间，如果在动画执行完毕前关闭modal就会出现问题(在调用ajax之后关闭modal遇到过这种问题)

**Comment by minwe** [comment]
dimmer 是一个单例，都是公用的，暂无法单独指定。dimmer 关闭的时候会判断是不是有其他的 Modal 还在使用 dimmer，有可能测试不完整或者是动画执行的问题，导致有时不能按预期工作。

**Comment by minwe** [comment]
暂时关闭，有其他问题再提。
