### ISSUE TITLE
使用webpack打包，必须在require里将jQuery导入到amazeui模块，不然浏览器console会提示focused not defined

### ISSUE THREAD

**Issue by sharkrice** [amazeui/amazeui#832]
使用webpack打包，必须在require里将jQuery导入到amazeui模块，不然浏览器console会提示`focused not defined`
但是，我已经通过ProvidePlugin将$、jquery、jQuery暴露给全局了。
`import 'imports?jQuery=jquery!amazeui'`

**Comment by minwe** [comment]
你是将 amazeui.js 也打包进去？

**Comment by minwe** [comment]
根据 Webpack 文档 https://webpack.github.io/docs/list-of-plugins.html#provideplugin，`ProvidePlugin` 插件并没有暴露全局模块的功能。

我们的实现是在 `externals` 里配置：

https://github.com/amazeui/starter-kit/blob/d70a7adad9d4228cf83f5994fb9a322f86db7efa/webpack.config.js#L104-L107

编写的时候仍然正常 `require`：

```javascript
var $ = require('jquery');
var AMUI = require('amazeui');

// 其他业务代码...
```

Webpack 打包的时候会把 `externals` 里的模块替换成全局的引用。

**Comment by ithack** [comment]
在html里用cdn的方式引入了jquery和amazeui，用webpack打包还是会报n(...).on is not a function的错误，求解，用了楼上解决方法并没有解决问题！！！！！！

**Comment by minwe** [comment]
@ithack Webpack `externals` 配置了吗？
