### ISSUE TITLE
TopBar控件react版在缩略模式下，点击菜单后，菜单不隐藏

### ISSUE THREAD

**Issue by flyzb618** [amazeui/amazeui#837]
TopBar控件react版在缩略模式下，点击菜单后，菜单不隐藏，请见附件，而jquery版没有这个问题。
![1](https://cloud.githubusercontent.com/assets/7271358/13106099/73572ed0-d5a1-11e5-8724-8a7adc89b70e.gif)

**Comment by minwe** [comment]
React 版有些功能不太完善，稍后看一下怎么处理。

以后 React 版本的问题请提到 https://github.com/amazeui/amazeui-react/issues，谢谢。

**Comment by minwe** [comment]
与 amazeui/amazeui-react#96 重复，这边的就先关闭了。
