### ISSUE TITLE
Bug: Tabs.Item安卓不兼容

### ISSUE THREAD

**Issue by linkaibin** [amazeui/amazeui#840]
**问题描述**

使用官方示例demo在安卓自带浏览器和webview内，使用Tabs.Item会出现
Uncaught TypeError: Object.assign is not a function
脚本运行报错导致无法显示

**产生环境**

- 操作系统及版本：三星Note3  5.0系统
- 浏览器及版本：安卓自带浏览器或webview
- 演示地址：http://t.amazeui.org/kitchen-sink/#/tabs?_k=ct117u

**复现步奏**

1. 进入就报错（必现）

**Comment by minwe** [comment]
amazeui/amazeui-touch#27 中已經解決，請等待更新，或者尝试在项目中加入 https://github.com/babel/babel/tree/development/packages/babel-plugin-transform-object-assign 插件。

Amaze UI Touch 的問題請反饋到相應項目裏 https://github.com/amazeui/amazeui-touch/issues，謝謝。
