### ISSUE TITLE
uCheck 使用 JS 选择时验证状态无效

### ISSUE THREAD

**Issue by dadait** [amazeui/amazeui#843]
## 问题描述

当在模态窗口中加入一个表单，并且使用了表单验证Form Validator，在提交表单时，验证根本没有起作用。

**Comment by minwe** [comment]
「表格验证」……

请提供可在线查看的演示，以便定位问题。

**Comment by dadait** [comment]
弄了段代码举例：  http://runjs.cn/detail/zqowmqic
点击“全部返选”，没有触发多选框的minchecked验证。
但是单个uCheck逐一点击没问题。

**Comment by minwe** [comment]
反选的时候 `trigger('change')` 以触发验证： 

```js
$('#check-download-form input').uCheck('toggle').trigger('change');
```

http://bin.amazeui.org/xebukipafu/edit?html,output

**Comment by dadait** [comment]
赞，谢谢，又了解了新技能√

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://raspberrypishop.ru/rare.php?2>

 

Again_moon@sohu.com
