### ISSUE TITLE
 iOS 虚拟键盘打开时 position:fixed 定位出错问题

### ISSUE THREAD

**Issue by menglongwang** [amazeui/amazeui#844]
**问题描述**

为避免是我自己代码问题，直接查看的是模板中的landing.html页面，
当顶部的Topbar 导航条固定在顶部显示时，在手机上点开任意一个表单输入框，弹出虚拟键盘后，然后往下滑动页面（不关闭虚拟键盘），顶部的Topbar 导航条就会滑动到页面中间了。。。
请问这个如何解决？谢谢

**产生环境**

- 操作系统及版本：ios9.
- 浏览器及版本：微信自带浏览器、chrome
- 演示地址：访问模板中landing.html页面即可
图在这里
http://ask.amazeui.org/?/question/608?notification_id=5034&rf=false&item_id=1161#!answer_1161

**复现步奏**

1. 打开landing.html页面
2. 下拉到表单位置
3. 点击任意输入框
4. 虚拟键盘弹出
5. 不关闭虚拟键盘，在页面位置（虚拟键盘上面的看得见页面的地方）往上滑动（手指是向下划）
6. 会发现顶部的Topbar定位出现bug，到了页面的中部

**Comment by minwe** [comment]
这是微信自身的问题（实测 iOS9 Chrome 49 没这个问题），无关 Amaze UI。

任意使用 `position: fixed` 的元素都会遇到这个问题，如：http://bin.amazeui.org/cafahoyomi

![img_2345](https://cloud.githubusercontent.com/assets/4370770/13661420/76d49a4c-e6cd-11e5-911a-003d37ebe84c.PNG)

常见的解决方式是使用绝对定位和容器内部滚动条来实现固定定位的效果。

**Comment by minwe** [comment]
- http://weblog.west-wind.com/posts/2015/Jun/05/IPad-Scroll-Issues-with-Fixed-Content
- https://remysharp.com/2012/05/24/issues-with-position-fixed-scrolling-on-ios
- https://github.com/scottjehl/Device-Bugs/issues/8
- http://code.tutsplus.com/tutorials/ios-5-fixed-positioning-and-content-scrolling--mobile-8332
- https://plus.google.com/+PaulIrish/posts/NZRMfyQUKud
- http://www.kylejlarson.com/blog/2011/fixed-elements-and-scrolling-divs-in-ios-5/

**Comment by minwe** [comment]
看这个[搜索结果](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=position%20fixed%20%E5%BE%AE%E4%BF%A1)或者下面的链接基本上能找到答案了。

- [修复position:fixed在ios虚拟键盘弹出时错位的bug](修复position:fixed在ios虚拟键盘弹出时错位的bug)
- [Web移动端Fixed布局的解决方案](http://efe.baidu.com/blog/mobile-fixed-layout/)
- [移动端web页面使用position:fixed问题总结](http://www.maxzhang.com/2013/07/%E7%A7%BB%E5%8A%A8%E7%AB%AFweb%E9%A1%B5%E9%9D%A2%E4%BD%BF%E7%94%A8position-fixed%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93/)

**Comment by menglongwang** [comment]
恩 非常感谢

**Comment by DFLovingWM** [comment]
同样遇到这个问题。谢谢分享
