### ISSUE TITLE
Datepicker 没有清除功能、Tab内的table响应式有问题

### ISSUE THREAD

**Issue by beijiaxu** [amazeui/amazeui#845]
## 问题描述

Datepicker没有清除日期按钮；
退格键删除框内的日期之后，再次点击日期操作无效。

Tab内的table宽度不能支持自适应（table是别的插件），在浏览器缩小到一定程度之后，table将不再缩小，且未达到min-width值

## 产生环境

- **设备：** 电脑
- **操作系统及版本：** win10
- **浏览器及版本：** chrome 48.0
- **演示地址：** 暂无

**Comment by minwe** [comment]
这个插件有删除功能：https://github.com/amazeui/datetimepicker

演示：http://amazeui.github.io/datetimepicker/docs/demo.html#%E5%B8%A6%E5%88%A0%E9%99%A4%E7%9A%84%E7%BB%84%E4%BB%B6%E5%BA%94%E7%94%A8

第二个可能不是 Tab 引起的，官网上的 Tabs 是可以缩放到很窄的。

**Comment by beijiaxu** [comment]
![qq 20160330100744](https://cloud.githubusercontent.com/assets/13776775/14136781/33824468-f697-11e5-8e08-080cf79fe18a.jpg)
![qq 20160330100753](https://cloud.githubusercontent.com/assets/13776775/14136783/38fd3042-f697-11e5-9c56-c1274369b26a.jpg)
![qq 20160330100805](https://cloud.githubusercontent.com/assets/13776775/14136784/3de34740-f697-11e5-9108-3717236dd486.jpg)

Tab缩放后会变成这样，但是左边不用tab的没什么影响

**Comment by minwe** [comment]
里面的表格设置了宽度？

**Comment by beijiaxu** [comment]
有个默认宽度和最小宽度，会根据浏览器缩放调整大小，但是tab里面的表格的min-width不起作用，最后的最小宽度比设置的要大一些

**Comment by minwe** [comment]
```css
.am-tabs-bd .am-tab-panel {
  padding: 10px 10px 15px;
}
```

Tab 内容本身有 `padding` 值，你可以设置为 0，看看效果如何。

没有能在线查看的演示我也无能为力。

**Comment by beijiaxu** [comment]
还是没效果。。

**Comment by xfworld** [comment]
又看到minwe的身影了，@beijiaxu 是不是你的布局存在问题，所以才会出现tab被挤走了....

**Comment by beijiaxu** [comment]
![qq 20160408135509](https://cloud.githubusercontent.com/assets/13776775/14375211/9c1a8cc8-fd91-11e5-9d78-cada4cc3d2b9.jpg)
![qq 20160408135525](https://cloud.githubusercontent.com/assets/13776775/14375215/9f9f3088-fd91-11e5-872b-45c0061d8d01.jpg)
@xfworld 我已经把能去掉的全去光了，就剩个table和tab，还是这样

**Comment by minwe** [comment]
没明白你到底想实现什么效果。

如果觉得太窄了没法用，你可以使用网格，在小屏幕上把他放到领一行去。

**Comment by beijiaxu** [comment]
如果我把窗口缩小，tab会挤过去，中间的margin没作用了，而且tab里面的table也会挤到tab外面。
实在不行我就换个布局吧。

**Comment by minwe** [comment]
嗯，你还是考虑调整一下布局吧。没有可查看的页面没办法提供解决方法。

前端这类的问题，演示既能准确传达问题，也利于问题快速解决。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://schluifer.at/rarely.php?a>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://stoneblueshoe.com/add.php?vkhfm>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://begatrading.com/practice.php?8h>

 

Again_moon@sohu.com

**Comment by NapChen** [comment]
你好，日期组件选取日期后，用backspace删除，再次选取日期输入框没有值的问题怎么解决？ @beijiaxu @minwe
