### ISSUE TITLE
模态窗口中的DataTable绑定后不显示数据

### ISSUE THREAD

**Issue by jiacx** [amazeui/amazeui#846]
如题，模态窗口中的绑定其他js组件也不行如uploadify

**Comment by minwe** [comment]
隐藏状态下可能无法初始化这些 DataTable 之类的插件，你试下 modal 打开的时候再初始化。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://cp92347.tmweb.ru/question.php?j>

 

Again_moon@sohu.com
