### ISSUE TITLE
用angularjs中的ui-view加载下拉列表失效

### ISSUE THREAD

**Issue by qzgyw** [amazeui/amazeui#849]
## RT

 放在主页没问题，放在ui-view子页面下拉功能就无效！全屏也这样！折叠面板是正常的！

## 产生环境

- **操作系统及版本：win10 64
- **浏览器及版本：Chrome 版本 50.0.2661.12

## 复现步奏

1.创建最简单的页面用ui-view加载带下拉列表的子页面，下拉功能失效，bootstrap的没问题

**Comment by minwe** [comment]
BS Dropdown 使用了事件委托，我们没有，需要在渲染完成以后初始化插件：

```js
$('xxx').dropdown();
```

参考 https://github.com/amazeui/amazeui/issues/480#issuecomment-84927084

**Comment by qzgyw** [comment]
官方demo中的开启全屏需要怎么初始化呢？

`<li class="am-hide-sm-only"><a href="javascript:;" id="admin-fullscreen"><span class="am-icon-arrows-alt"></span> <span class="admin-fullText">开启全屏</span></a></li>`

@minwe

**Comment by minwe** [comment]
https://github.com/amazeui/amazeui/blob/master/docs/examples/assets/js/app.js
