### ISSUE TITLE
Datepicker选择日期后能否在文本框里显示“2016年1月1日”这样的日期格式？

### ISSUE THREAD

**Issue by shaohao2014** [amazeui/amazeui#851]
Datepicker选择日期后能否在文本框里显示“2016年1月1日”这样的日期格式？

另外：用$("#date").val(new Date())之后，再点击Datepicker选择日期后，文本框的Value不再变化，怎么回事？难道datepicker的click事件无效了？

**Comment by minwe** [comment]
> `forma`t: 日期格式，默认为 `yyyy-mm-dd`，可以选择 `yy/mm/dd` 、`mm/dd`、`dd/mm/yyyy`、`dd/mm/yy`、`dd/mm`等，中间分隔符可以使用 `/`、`-`、` `。

目前不支持上述以外的日期格式。

要设置日期可以使用：

```js
 $('#date').datepicker('setValue', new Date());
```

http://bin.amazeui.org/zoyemevizu/edit?html,output
