### ISSUE TITLE
Bug: QQ浏览器不支持flex-warp

### ISSUE THREAD

**Issue by msisliao** [amazeui/amazeui#852]
**问题描述**

（描述一下问题）

**产生环境** 

- 操作系统及版本：安卓4.4
- 浏览器及版本： QQ浏览器
- 演示地址：http://t.amazeui.org/#/?_k=e3wfmf

**复现步奏**

1.扫二维码进入demo 移动端的 其中icon组件不会换行（原因是flex-wrap）
2. 
...

**Comment by minwe** [comment]
Move to amazeui/amazeui-touch#12.

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://xn--80agplckg.xn--p1ai/persian.php?a6251>

 

Again_moon@sohu.com
