### ISSUE TITLE
管理后台示例页脚 CSS 样式优化问题

### ISSUE THREAD

**Issue by BladeCode** [amazeui/amazeui#853]
**问题描述**

使用AmazeUI框架，使用非笔记本分辨率常用的显示器上，当页面布局内容小于屏幕显示内容时，此时页面布局的footer会上移，不能停留在浏览器底部，在大屏幕上，此显示效果非常不理想

**环境**

- 设备：Windows 1920x1080分辨率显示器
* 异常图片
![AmazeUI-Bug](http://7xs1zb.com1.z0.glb.clouddn.com/AmazeUI-Bug.png)

**Comment by minwe** [comment]
非固定定位的固定页脚实现参考：

- https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/
- http://cbracco.me/css-sticky-footer-effect/
- https://css-tricks.com/snippets/css/sticky-footer/
- http://ryanfait.com/resources/footer-stick-to-bottom-of-page/

我们会抽时间完善一下这个示例。
