### ISSUE TITLE
Prompt关闭时打印古怪字符串

### ISSUE THREAD

**Issue by Cospotato** [amazeui/amazeui#854]
## 问题描述

Prompt触发`close.modal.amui`事件时控制台打印字符串“sdafdf”

## 产生环境

- 任意设备
- 任意操作系统
- 任意浏览器
- 木有地址

## 复现步奏

1.创建一个Prompt
2.js里调用它
3.关闭Prompt

## 修改建议
删除amazeui.js第5140行的代码

嗯就酱

**Comment by Cospotato** [comment]
哦豁，怪我，新版本已经修复惹

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://www.kidzlife.co.nz/vessel.php?hcv>

 

Again_moon@sohu.com
