### ISSUE TITLE
日期组件能不能格式化出来时分秒

### ISSUE THREAD

**Issue by mqliutie** [amazeui/amazeui#855]
## 日期组件能不能格式化出来时分秒

（简明扼要地描述一下问题）

## 产生环境

- **设备：**  PC

由于设置开始时间要求很精确的,所以要有时分秒,我看介绍的时候好像只有 : 
**format: 日期格式，默认为 yyyy-mm-dd，可以选择 yy/mm/dd 、mm/dd、dd/mm/yyyy、dd/mm/yy、dd/mm等，中间分隔符可以使用 /、-、。**

不知道妹子提供没,如果没提供是不是就要再引插件了

**Comment by minwe** [comment]
没有时分秒功能。参考 https://github.com/amazeui/datetimepicker 或者使用其他插件。

**Comment by mqliutie** [comment]
完美
