### ISSUE TITLE
与Angular的兼容问题

### ISSUE THREAD

**Issue by tcrow** [amazeui/amazeui#857]
## 问题描述

我最近在尝试整合amazeui框架与angular，发现部分功能可能会出现问题，目前发现Tabs这个组件会出现问题。

## 产生环境

- **设备：**（手机、平板等移动设备时填写此项）
- **操作系统及版本：**
- Chrome 版本 49.0.2623.87 m
- 无

## 复现步奏
无

官方默认Tabs使用的href标签是href="#elementId"
这种方式在angular下会默认跳转到angular的router
建议可以增加配置，允许替换成其他符号，我尝试改了amezeui的源代码，用@符号代替原来的#目前可以正常使用

```js
var regexHash = /^@.+$/;
	  var $target = regexHash.test(href) && this.$content.find(href.replace('@',"#")) ||
	    this.$tabPanels.eq(activeIndex);
```

使用：

```html
 <div class="am-tabs am-margin" data-am-tabs>
           <ul class="am-tabs-nav am-nav am-nav-tabs">
                <li class="am-active"><a href="@tab1">基本信息</a></li>
                <li><a href="@tab2">详细描述</a></li>
                <li><a href="@tab3">SEO 选项</a></li>
            </ul>
```

**Comment by minwe** [comment]
如果插件已经初始化的成功的话应该会阻止默认的链接跳转行为的。

Angular 这种动态渲染的场景需要在 Tabs 的结构渲染完成后，调用初始化接口 `$('[data-am-tabs]').tabs()`，否则应该不能正常工作。

链接也可以使用其形式，`#xxx` 不是必需的。

```html
<ul class="am-tabs-nav am-nav am-nav-tabs">
    <li class="am-active"><a href="javascript: void(0)">流浪</a></li>
    <li><a href="javascript: void(0)">流浪</a></li>
    <li><a href="javascript: void(0)">再流浪</a></li>
</ul>
```

**Comment by tcrow** [comment]
非常感谢，试了一下您提供的方法，果然不用修改源代码也能正常工作了，只是需要在页面加载完成以后主动调用一次初始化接口
`$('[data-am-tabs]').tabs()`

**Comment by minwe** [comment]
客气。

建议你了解一下 jQuery 事件绑定机制，跟 Angular 的动态绑定有一些区别。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://xn--d1acqcdjbv4b8d.xn--p1ai/guy.php?g>

 

Again_moon@sohu.com
