### ISSUE TITLE
iOS 微信上 am-table 宽度超出宽度后，边框未能包住单元格

### ISSUE THREAD

**Issue by hee93** [amazeui/amazeui#859]
## 问题描述

在手机上am-table边框 不能完整包住整个table 但在chrome下模似手机它就可以包住整个table

## 产生环境

- **设备：ip5s 
- **操作系统及版本：9.3.1
- **浏览器及版本：微信浏览器 uc浏览器
- **演示地址：**

...

**Comment by minwe** [comment]
在 iPhone 6 Plus 微信上测了一下 http://amazeui.org/css/table，没发现你说的问题。

能截个图吗？

**Comment by hee93** [comment]
<div class=" am-scrollable-horizontal">
<table class="am-table am-table-bordered am-table-striped am-text-nowrap">
  <thead>
    <tr>
      <th>开始时间</th>
      <th>结束时间</th>
      <th>订单金额</th>
      <th>下单时间</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>2015-01-01</td>
      <td>2015-01-01</td>
      <td>100.00</td>
      <td>14156488979</td>
    </tr>
    <tr>
      <td>2015-01-01</td>
      <td>2015-01-01</td>
      <td>100.00</td>
      <td>14156488979</td>
    </tr>
  </tbody>
</table>
</div>
http://substr.cn/286055708186223575.jpg

**Comment by minwe** [comment]
确实有这样的问题，不过无从处理。

建议你换一种方式排列订单，在手机上横向滚动表格体验也不好。

如果你非要用的话，可以考虑把边框移到单元格上：

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <meta name="viewport" content="width=device-width">
  <meta name="format-detection" content="telephone=no">
  <link rel="stylesheet" href="css/amazeui.min.css">
  <style>
    body {
      padding: 5px;
    }

    .my-table {
      border: none;
    }

    .my-table thead th {
      border-top: 1px solid #ddd!important;
    }

    .my-table tr th:last-child,
    .my-table tr td:last-child {
      border-right: 1px solid #ddd;
    }

    .my-table tbody tr:last-child td {
      border-bottom: 1px solid #ddd;
    }
  </style>
</head>
<body>

<div class=" am-scrollable-horizontal">
  <table class="am-table am-table-bordered am-table-striped am-text-nowrap my-table">
    <thead>
    <tr>
      <th>开始时间</th>
      <th>结束时间</th>
      <th>订单金额</th>
      <th>下单时间</th>
    </tr>
    </thead>

    <tbody>
    <tr>
      <td>2015-01-01</td>
      <td>2015-01-01</td>
      <td>100.00</td>
      <td>14156488979</td>
    </tr>
    <tr>
      <td>2015-01-01</td>
      <td>2015-01-01</td>
      <td>100.00</td>
      <td>14156488979</td>
    </tr>
    </tbody>
  </table>
</div>

</body>
</html>
```

**Comment by hee93** [comment]
好的 谢谢
