### ISSUE TITLE
Selected 点开下拉选框，点击已经选择的项，下拉选框不会回弹

### ISSUE THREAD

**Issue by zhangaoqi** [amazeui/amazeui#860]
## 问题描述

点开下拉选框，点击已经选择的项，下拉选框不会回弹。这不科学啊。

## 产生环境

- **操作系统及版本：**Windows10
- **浏览器及版本：**Chrome

**Comment by zhangaoqi** [comment]
补充：是下拉选框Selected，不是下拉组件DropDown。

**Comment by minwe** [comment]
- 有 `multiple` 属性的时候（多选）不会关闭；
- 没有（单选）会自动关闭。

**Comment by zhangaoqi** [comment]
@minwe 可以我并没有设置multiple属性啊，我就是用的单选呀，比如我现在选中了第二项。当我再点开下拉选框，再次点击第二项时下拉框还是没有关闭。除非是选择了除第二项以外的其他项（也就是当前未选择的项）的时候才会关闭，并触发onchange事件。

**Comment by minwe** [comment]
不选择新的选项为啥要点开再点击一下呢？也是够闲的。你可以点下来框以外的内容关闭。

**Comment by zhangaoqi** [comment]
@minwe 但是你不能说用户就不这样用啊，有可能他点开本来想选择其他什么选项，结果点击了选项发现本来就是选对了的。关键是原生的selected就是这样，有些苛刻的用户用起来就觉得奇怪。

**Comment by minwe** [comment]
也是吧，虽然点其他区域也可以关闭。
