### ISSUE TITLE
动态插入的 DOM 如何手动初始化？

### ISSUE THREAD

**Issue by cenxun** [amazeui/amazeui#864]
## 问题描述

>  动态添加一个 包含若干组件的form，样式未生效，怎么对这个表单进行重新渲染？

## 截图
渲染
![default](https://cloud.githubusercontent.com/assets/5516946/14841779/f7389b86-0c73-11e6-82f4-ee09127cb6e3.jpg)

动态添加
![default](https://cloud.githubusercontent.com/assets/5516946/14841784/0ae683e6-0c74-11e6-9127-ce32b51062c3.jpg)

谢谢！

**Comment by minwe** [comment]
你用的是什么？Selected?

插入以后调用初始化接口：

```javascript
$('[data-am-selected]').selected();
```

**Comment by cenxun** [comment]
OK了，冒昧再问下，我直接  append 的，这是 select ，请问其他组件会么？

**Comment by minwe** [comment]
其他也一样，动态插入的都需要手动初始化。默认的初始化行为都是在 `ready` 事件里进行的，插入的 DOM 已经过了这个时机。

**Comment by cenxun** [comment]
谢谢！
