### ISSUE TITLE
禁用响应式的情况下。topbar内容超出窗口无法显示

### ISSUE THREAD

**Issue by angrydigital** [amazeui/amazeui#867]
## 问题描述

禁用响应式的情况下。固定的topbar的内容超出窗口，无法显示，即使拉动横滚轴，topbar内容也无法滚动。还有就是禁用响应式只是单纯的对内容禁用，而不是对全部禁用。例如topbar在640以下就会缩了。

## 产生环境

- **设备及型号：PC
- **操作系统及版本：win10
- **浏览器及版本：chrome50
- **演示地址：没有
- **问题截图/录屏：**

**Comment by minwe** [comment]
对于非响应式，Amaze UI 只是提供可能的使用方式的例子，至于使用中遇到的各种问题，无法做支持，需要用户自行编写代码解决。

Amaze UI 是基于移动优先、响应式的理念开发的，再增加一些针对非响应式的代码违背了基本理念。
