### ISSUE TITLE
Bug: 日期输入框显示问题

### ISSUE THREAD

**Issue by xiaoxinpro** [amazeui/amazeui#868]
**问题描述**
日期输入框`<input type="date"  value="2016-5-4 20:06:20">`无法显示value值
并且在Safari浏览器中输入框的大小出现异常

**产生环境**

- 设备：iPhone 和 PC
- 操作系统及版本：IOS9.3 和 win10
- 浏览器及版本：Safari 和 chrome
- 演示地址：

**复现步奏**

1. 使用Amaze UI模板
2. 加入`<input type="date"  value="2016-5-4 20:06:20">`

**Comment by minwe** [comment]
不显示 `value` 是浏览器问题，跟 Amaze UI 无关，把 Amaze UI 的 CSS 删了一样不显示。

http://bin.amazeui.org/besoluzazo/edit?html

在  iOS 版 Safari 上应该是需要给 `[type="date"]` 设置高度，这也算是浏览器的问题吧。

http://stackoverflow.com/questions/18967852/input-type-date-in-ios-7

**Comment by xiaoxinpro** [comment]
@minwe 
![qq 20160505151439](https://cloud.githubusercontent.com/assets/11443745/15038201/5036affa-12d4-11e6-9326-049d90a5c2a7.jpg)

不显示 `value `并不是浏览器的问题, 我使用标准的HTML5, 在任何浏览器中都可以正常显示`value`, 也没有输入框高度异常的现象!
