### ISSUE TITLE
请教一下，妹子UI的BUTTON在苹果手机上异常

### ISSUE THREAD

**Issue by czping** [amazeui/amazeui#869]
在微信游览器中，苹果手机对button无法点击，安卓的却可以，苹果点击按钮区域就像选择了按钮中的文字

**Comment by minwe** [comment]
请给出具体演示代码以及手机型号、微信版本等信息。

**Comment by czping** [comment]
<!doctype html>
<html class="no-js">
<head>
  <base href="<?php  echo base_url();?>"/>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="<?php echo $systemdescription;?>">
  <meta name="keywords" content="<?php echo $systemkeywords;?>">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title><?php echo $systemname?></title>
  
  <meta name="renderer" content="webkit">
  
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <link rel="icon" type="image/png" href="assets/i/favicon.png">
  
  <meta name="mobile-web-app-capable" content="yes">
  <link rel="icon" sizes="192x192" href="assets/i/app-icon72x72@2x.png">
  
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="<?php echo $systemname?>"/>
  <link rel="apple-touch-icon-precomposed" href="assets/i/app-icon72x72@2x.png">
  
  <meta name="msapplication-TileImage" content="assets/i/app-icon72x72@2x.png">
  <meta name="msapplication-TileColor" content="#0e90d2">
  
  <link rel="stylesheet" href="assets/css/amazeui.min.css"/>
  <link rel="stylesheet" href="assets/css/admin.css">

</head>
<body>

<div class="am-g">
  <div class="am-cf am-u-sm-12 "> 
  <form action="home/register/index/5" method="POST" id="doc-vld-msg">  
  <table >
    <tbody>
      <tr >
        <td style="width:100%"><img src="<?php echo $mainpic;?>" alt="" style="width:100%"></td>
      </tr>
      <tr >
        <td><?php echo $htmlData; ?></td>
      </tr>
      <tr>
        <td>          
            亲~<strong style="color:red"><?php echo $nickname; ?></strong>填写报名表参加哦
          <hr>                    
        </td>
      </tr>
      <tr>
        <td>
        <div class="am-g">
          <div class="am-u-sm-4 am-text-right">填写姓名</div>
          <div class="am-u-sm-8 ">
            <input type="text" name="registername"  required class="am-form-field am-round am-text-center" placeholder="填写联系姓名" <?php if ($posted) {    echo "value='".$registername."' ";        } ?>>
          </div>
        </div>           
        </td>
      </tr>
      <tr>
        <td>
         &nbsp;
        </td>
      </tr>
      <tr>
        <td>             
        <div class="am-g">
          <div class="am-u-sm-4 am-text-right">联系方式</div>
          <div class="am-u-sm-8 "><input type="text" name="registerphone" required class="am-form-field am-round am-text-center" placeholder="填写联系方式" <?php if ($posted) {    echo "value='".$registerphone."' ";        } ?>></div>
        </div>
        </td>
      </tr>
      <tr>
        <td>
         &nbsp;
        </td>
      </tr>
      <tr>
        <td>
          <div class="am-g">
            <div class="am-u-sm-6 ">
              <label class="am-radio-inline am-fr">
              <input type="radio"  value="1" name="selecttype" class="am-input-lg" checked <?php if ($posted) {echo "disabled";} ?>> 学生
              </label>
            </div>
            <div class="am-u-sm-6 ">
              <label class="am-radio-inline am-fl">
              <input type="radio"  value="2" name="selecttype" class="am-input-lg" <?php if ($posted) {echo "disabled";} ?>> 教职工
              </label>
            </div>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          &nbsp;
        </td>
      </tr>
      <tr>
        <td>
        # <div class="am-cf">
**          <button type="button" id="btn" class="am-btn am-btn-danger am-round am-center " 
          <?php if ($posted>=2) {echo "disabled";}?>><i class="am-icon-heart"></i><?php switch ($posted) {
            case 0:
              echo "我要报名,也要抽红包！";
              break;
            case 1:
              echo "你已报名,抽红包吧";
              break;
            case 2:
              echo "你已报名,已抽过了哦";
              break;
            case 4:
              echo "发完啦，现场抽奖再来吧";
              break;
          }?>
          </button>**
          </div>
        </td>
      </tr>
    </tbody>
  </table>
  </form>
  </div>
</div>
<hr>
<footer >
  
    <div class="am-cf">
      <strong class="am-text-center" style="display:block;color:#999b9e;font-size: 1.2rem">系统授权：<?php echo $authorization;?></strong>
      <small class="am-text-center" style="display:block;color:#999b9e;font-size: 1.1rem">CopyRight By <?php echo $webroot;?> </small>
      <small class="am-text-center" style="display:block;color:#999b9e;font-size: 1.1rem"><?php echo $web_license;?> </small>
    </div>
</footer>
<div class="am-modal am-modal-loading am-modal-no-btn" tabindex="-1" id="my-modal-loading2">
  <div class="am-modal-dialog">
    <div class="am-modal-hd"></div>
    <div class="am-modal-bd" style="width: 100%">
      <img src="assets\images\loading2.gif" alt="" ><br>
      <span class="am-text-sm">正在提交报名</span>
    </div>
  </div>
</div>


<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/amazeui.min.js"></script>
<script src="assets/js/app.js"></script>
<script>
  $(function(){    
    $("#btn").click(function() {
        $("input").each(function(){ //对表单中所有INPUT进行遍历，若有其他表单控件再加入即可
        $(this).focus();
      });
       if ($('#doc-vld-msg').validator('isFormValid')) { //检查表单状态
            $("#my-modal-loading2").modal("open");
            setTimeout(' $("#doc-vld-msg").submit()',300);//刷新当前页面.   
       }else{
       }
    });
  })
</script>
</body>
</html>

**Comment by czping** [comment]
问题找到了，苹果手机必须要加载这段

**Comment by minwe** [comment]
应该跟这个没关系，如果你还在用 2.1 的话，可以尝试升级到最新的版本。

我测试了一下 http://bin.amazeui.org/fewepujovu/1 没问题。
