### ISSUE TITLE
thymeleaf 不能使用 data-am-scrollspy-nav="{offsetTop: 45}" data-am-sticky

### ISSUE THREAD

**Issue by shellyxue** [amazeui/amazeui#870]
## 问题描述
 thymeleaf 不能使用 data-am-scrollspy-nav="{offsetTop: 45}" data-am-sticky

## 产生环境

![image](https://cloud.githubusercontent.com/assets/13460709/15206861/d5ac3bc0-1854-11e6-8b47-3c33c73d9bef.png)

![image](https://cloud.githubusercontent.com/assets/13460709/15206899/130ee63e-1855-11e6-9578-793a89d05d7c.png)

解析通不过

## 复现步奏
1.
spring 集成thymeleaf模板引擎 ,首页搜索栏使用
         
![image](https://cloud.githubusercontent.com/assets/13460709/15207052/f86f9bce-1855-11e6-858f-f597fec9bae9.png)

错误

**Comment by shellyxue** [comment]
希望能有好的解决办法，谢谢各位作者

**Comment by minwe** [comment]
应该是花括号解析错误吧，你把 `{}` 转义一下应该就没有问题了。

我没用过这个模板引擎，具体怎么转义请查看模板引擎的文档。
