### ISSUE TITLE
在webpack中如何require less文件？

### ISSUE THREAD

**Issue by Catlite91** [amazeui/amazeui#871]
## 问题描述

如何使用webpack按需打包，比如我只用到button，则require('amazeui/less/button.less')

**Comment by minwe** [comment]
可以试下创建了一个 Less 文件，引入 Button 相关依赖，然后再 require 这个文件：

```css
// button.less
@import "node_modules/amazeui/less/variables";
@import "node_modules/amazeui/less/button";
@import "node_modules/amazeui/less/button-group";
```

```javascript

**Comment by Catlite91** [comment]
编译variables.less的时候报错了，
Module build failed: ModuleBuildError: Module build failed: error evaluating function `floor`: argument must be a number (line 104, column 26)
floor是依赖了哪个文件？

**Comment by Catlite91** [comment]
是否可以参考下ant-design的做法，然后添加个babel插件
https://github.com/ant-design/ant-design
https://github.com/ant-design/babel-plugin-antd

**Comment by minwe** [comment]
漏了个文件 `mixins.less`：

```css
// button.less
@import "node_modules/amazeui/less/variables";
@import "node_modules/amazeui/less/mixins";
@import "node_modules/amazeui/less/button";
@import "node_modules/amazeui/less/button-group";
```

**Comment by Catlite91** [comment]
e。好像仍旧是同样的错误❌

**Comment by minwe** [comment]
那应该就是 Webpack 配置或者相关 loader 的问题了 ，`lessc button.less` 没问题。

**Comment by Catlite91** [comment]
ok了，是strictMath的问题
