### ISSUE TITLE
Select下拉框在tab选项卡里面显示有问题

### ISSUE THREAD

**Issue by mysggx** [amazeui/amazeui#872]
![qq 20160520132606](https://cloud.githubusercontent.com/assets/19484314/15418048/9f8eb0aa-1e8e-11e6-8598-6aee70cba73a.png)

## 问题描述

（在tab选项卡里，下拉框显示背景色变成灰色，而不是透明色）

## 产生环境

- **设备及型号：**（手机、平板等移动设备时填写此项，如 `iPhone 6s Plus`）
- **操作系统及版本：**（win10）
- **浏览器及版本：**（google浏览器）
- **演示地址：**（http://139.196.14.192:8080/problemSelect.html）
- **问题截图/录屏：**

  
![qq 20160520132606](https://cloud.githubusercontent.com/assets/19484314/15418059/b94290fc-1e8e-11e6-8cb3-5f17851a3691.png)

**Comment by minwe** [comment]
这里是有点小问题，Tab 的 active 状态影响到了 Dropdown。

不过 Dropdown 用的是 Button，即便修复 Tab 的影响以后，也是有背景的。

**Comment by mysggx** [comment]
非常感谢您的回答，我自己摸索了下，button的背景色为灰色，我试着把button背景色变成白色。
 $(".am-selected-btn").css("background-color","white");
目前我想到的办法是这样做，不知道有没有更好的办法。

**Comment by minwe** [comment]
暂时没有。Button 目前没有背景透明、只有边框的样式，后续会考虑是否增加。

**Comment by mysggx** [comment]
好的，非常感谢
