### ISSUE TITLE
面包屑导航content中的编码问题

### ISSUE THREAD

**Issue by ycjcl868** [amazeui/amazeui#878]
![image](https://cloud.githubusercontent.com/assets/13595509/15645660/636246d6-268c-11e6-824f-6e479f5d69bd.png)
下载下来就是用的utf-8编码，结果还是出现了乱码。

**Comment by minwe** [comment]
你是从什么渠道下载的呢？

**Comment by ycjcl868** [comment]
官网

**Comment by minwe** [comment]
我试了一下，无法重现乱码问题，不过还是改成 Unicode 编码了。
