### ISSUE TITLE
无法通过点击遮罩层关闭Modal

### ISSUE THREAD

**Issue by baryon** [amazeui/amazeui#882]
下面的代码来自 http://amazeui.org/javascript/modal 的第一个例子，只是把closeViaDimmer的值改为true，按照描述可以应该点击遮罩层关闭Model，事实并非如此。

```
<button
        type="button"
        class="am-btn am-btn-primary"
        data-am-modal="{target: '#doc-modal-1', closeViaDimmer: true, width: 400, height: 225}">
    Modal
</button>

<div class="am-modal am-modal-no-btn" tabindex="-1" id="doc-modal-1">
    <div class="am-modal-dialog">
        <div class="am-modal-hd">Modal 标题
            <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
        </div>
        <div class="am-modal-bd">
            Modal 内容。本 Modal 应该可以通过遮罩层关闭。
        </div>
    </div>
</div>
```

**Comment by minwe** [comment]
默认是可以通过遮罩层关闭的， 如果不禁用就不用加这个选项，当然加了设置为 `true` 也没有什么负作用。

http://bin.amazeui.org/cufufosaro/edit?html,output 

你遇到的问题可能出在其他的地方。

**Comment by baryon** [comment]
我是说：加了true，也**无法通过遮罩层关闭**
我用最新版的safari和chrome都无法点击model以外的地方关闭这个model，不像popup一样

**Comment by baryon** [comment]
晕倒了，2.5/2.7在bin模拟环境里确实可以关闭，但是在我这里只有2.5是OK的，2.7关闭不了，我需要找到原因

**Comment by baryon** [comment]
问题出在2.7的css上

http://bin.amazeui.org/zogihiqebe/1/edit?html,output

**Comment by minwe** [comment]
哦，2.6 以后版本的 Modal 布局实现上有一些调整，已经点不到 dimmer 了。

我看看怎么处理一下。
