### ISSUE TITLE
网格不能自适应内容的高度

### ISSUE THREAD

**Issue by baryon** [amazeui/amazeui#883]
普通的网格布局无法自适应高度，布局受内容的多少影响，一个文字很少的block就会导致整体串位。比如下面的例子，调整view的宽度，会看到布局发生很大的变化，有的block站了一行，还偏右侧。
网格布局

http://bin.amazeui.org/xotoxuxeqi/1/edit?html,output

只好采用等分网格布局。从html角度看，div和ul是不一样的东西，如果div可以很好的表现，那么不应该用ul

http://bin.amazeui.org/mobukoqifi/edit?html,output

**Comment by minwe** [comment]
浮动布局的缺点就是这样的，可以使用 https://github.com/mattbanks/jQuery.equalHeights 之类插件。

一般而言，网格只考虑一行的情形。对于多行的排列用等分网格比较合适，从语义化上来讲用 `ul` 并无不妥。

**Comment by baryon** [comment]
Amazeui应该内置对应的机制，否则说一行里的元素有时是3个，有时是两个，有时是1个，而且超过两行的话，就是不可能美观的了。
2016年6月8日(水) 17:50 Minwe LUO <notifications@github.com>:
