### ISSUE TITLE
网格居中am-u-sm-centered导致popover无法弹出

### ISSUE THREAD

**Issue by baryon** [amazeui/amazeui#884]
有问题的示例如下：

http://bin.amazeui.org/xigunapine/1/edit?html,output

正常的demo

http://bin.amazeui.org/rereyugicu/1/edit?html,output

但是我要的就是居中的效果

**Comment by baryon** [comment]
sorry，加一个小白问题，如何不用网格，居中显示两个图片在一行上？

**Comment by minwe** [comment]
```html
<div class="am-u-lg-6 am-u-md-8 am-u-sm-12 am-u-sm-centered am-cf">
```

你在居中的网格上加上浮动清除，不然点不动图片，自然不会触发事件。

水平居中可以通过以下几种方式实现：

- `text-align: center`: 适用于 `inline` 和 `inline-block` 的元素
- ` margin-left` 和 `margin-right` 的值设置为 `auto`，适用于单个 block 元素
- flexbox: 适用于多个 block 子元素


具体参考：

- http://jsbin.com/tadagekahu/1/edit?html,output
- http://www.w3schools.com/css/tryit.asp?filename=trycss_align_container
- https://css-tricks.com/centering-css-complete-guide/

**Comment by baryon** [comment]
thanks
