### ISSUE TITLE
select绑定了onchange事件之后提交表单数据不正常

### ISSUE THREAD

**Issue by zeroabc** [amazeui/amazeui#885]
## 问题描述

select绑定了onchange事件之后提交表单数据不正常，
服务器接收到的表单数据并不是select选择的值，（接收到的是select初始化的值，详细看下面步骤）
ps1:前端我提交表单前触发了` $("#form").validator('isFormValid'); `表单验证，不知道有无影响
ps2:若select没有绑定onchange,则不会出现4中的问题
ps3:我现在暂时的处理办法:
```
$(document).ready(function(){
                	var ccc = 0;
                	$('#industryCombo').on('change', function() {
                		       //跳过触发两次change?BUG???-----start
        				var classStr = "";
        				if ($(this).attr('class')) {
        					classStr += $(this).attr('class');
        				}
        				//console.log(ccc);
        				if (ccc<1 && classStr.indexOf("am-field-valid")>-1) {
        					ccc++;
        					return;
        				}
        				//跳过触发两次change?BUG???-----end
                		
                		        .........
        			});
            	});
```
这样处理之后就不会有标题的问题，但是每次都插入这样一段代码想当恶心。
具体原因是什么我不清楚，希望能修复一下这个这个bug。

## 产生环境

遨游浏览器极速模式、谷歌浏览器均有同样的问题

## 复现步奏

1.select绑定了onchange
2.更改select选择的值
3.提交表单
4.服务器接不到上面选择的值（接收到的是select初始化的值）

**Comment by xfworld** [comment]
你需要查看select的渲染方法，看看是否生效了

**Comment by zeroabc** [comment]
@xfworld 
我是这样写的，只要带上data-am-selected属性就会自动渲染成amaze的select的吧？

`<select id="industryCombo" name="company.industryId" data-am-selected="{searchBox: 1,placeholder: '请选择行业',btnSize: 'sm',maxHeight: '260px'}" required>
    <optgroup label="--">
        <option value=" ">无</option>
    </optgroup>
    <c:forEach var="item" items="${industryGroup}">
        <optgroup label="${item.key}">
            <c:forEach items="${item.value}" var="industry">
                <option value="${industry.getId()}" <c:if test="${industry.getId() ==entity.get('industryId')}">selected</c:if>>${industry.get('name')}</option>
            </c:forEach>
        </optgroup>
    </c:forEach>
</select>
<script type="text/javascript">
    $(document).ready(function() {
        var ccc = 0;
        $('#industryCombo').on('change', function() {
            //跳过触发两次change?BUG???-----start
            var classStr = "";
            if ($(this).attr('class')) {
                classStr += $(this).attr('class');
            }
            //console.log(ccc);
            if (ccc < 1 && classStr.indexOf("am-field-valid") > -1) {
                ccc++;
                return;
            }
            //跳过触发两次change?BUG???-----end
            var v0 = $('#industryCombo').val();
            if (v0 == ' ') {}
            $('#industryCombo1').selected('select', 0);
            $('#industryCombo2').selected('select', 0);
        });
    });
</script>`

**Comment by minwe** [comment]
可能是 #880 中的问题引起的。

你用的是什么版本的？

搜索 `this.observer.observe(this.$element[0], {`，把后面的 `attributes: true,` 删掉，看看问题还存不存在。

**Comment by zeroabc** [comment]
@minwe 
原来是用2.6.1的，有这个问题，然后换了最新的2.7.0还是有这个问题

我搜了一下只有这句
this.observer.observe(this.$element[0],{childList:!0,attributes:!0,subtree:!0,characterData:!0})，没有attributes

**Comment by minwe** [comment]
`2.7.0` 也是有问题的，修复的版本还没有发布。

你可以先用着自己替换的版本，等新版本发布以后更新一下就行。

**Comment by minwe** [comment]
Duplicated of #880.
