### ISSUE TITLE
关注中...

### ISSUE THREAD

**Issue by eyeA** [amazeui/amazeui#886]
> 欢迎你为 Amaze UI 添砖加瓦。
>
> - 如果你想反馈 bug 或者使用问题，请**务必**按照以下格式提交，以便问题定位和解决，节省来回问答的时间；
> - 如果你不熟悉 Markdown 语法，请先阅读 [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)；
> - 如果你不知道如何上传文件，请参考 [File attachments on issues and pull requests](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)，或者留意一下输入框底部的小字 `Attach files by dragging & dropping, selecting them, or pasting from the clipboard.`，点击 **selecting them** 也可以上传；
> - 最后，请在提交 issue 之前删除提示性的文字，包括本行及以上部分，以及下面括号中的内容。

## 问题描述

（简明扼要地描述一下问题）

## 产生环境

- **设备及型号：**（手机、平板等移动设备时填写此项，如 `iPhone 6s Plus`）
- **操作系统及版本：**（在系统设置关于里面可以查看）
- **浏览器及版本：**（一般在浏览器「帮助」或者「关于」里面）
- **演示地址：**（请尽量提供可在线查看的演示地址）
- **问题截图/录屏：**

  （截图和录屏有助于我们更直观的理解你想表达的问题。如果需要，你可以使用 [LICEcap](http://www.cockos.com/licecap/) 录制 GIF 动画）

## 复现步奏

1.
2.
...

**Comment by minwe** [comment]
谢谢关注！
