### ISSUE TITLE
360安全浏览器（8.1）下图片轮播（slider）重新展示第一张图片时，整体会闪一下

### ISSUE THREAD

**Issue by sooxin** [amazeui/amazeui#891]
## 问题描述

当在360安全浏览器（8.1）中浏览slider图片轮播的时候，轮播图片从最后一幅循环跳转到第一幅时，图片整体会闪一下。360极速浏览器未作测试。win0上IE和edge，ubuntu16上firefox无此种情况。
## 产生环境
- **设备及型号：**笔记本和电脑
- **操作系统及版本：**win7&win10
- **浏览器及版本：**360浏览器版本8.1.1 内核版本45.0
- **演示地址：**http://amazeui.org/javascript/slider
## 复现步奏
1. 进入文档页http://amazeui.org/javascript/slider
2. slider的第一个demo，等待图片从第一幅展示到第四幅（最后一幅）
3. 当图片从第四幅转到第一幅时就出现图片一闪的情况
   ...

**Comment by minwe** [comment]
把 Slider 单独提出来以后问题就无法重现了，你自己有在别的地方使用出现类似的问题的吗？

http://bin.amazeui.org/saticigalic?html,output
