### ISSUE TITLE
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序或批处理文件。

### ISSUE THREAD

**Issue by myunite** [amazeui/amazeui#892]
**问题描述**

npm start能够跑得起来，
npm run build 执行后报错误:
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chuncn-win10\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! amazeui-touch@1.0.0-rc.1 build: `NODE_ENV=production gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amazeui-touch@1.0.0-rc.1 build script 'NODE_ENV=production gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the amazeui-touch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs amazeui-touch
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls amazeui-touch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\Users\chuncn-win10\Desktop\[Amaze UI]\amazeui-touch\npm-debug.log

**产生环境**
windows cmd或git brash

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36
```

**Comment by minwe** [comment]
重新 push 一下代码，或者使用 `set NODE_ENV=production&&gulp build` 。
