### ISSUE TITLE
macOS下 sudo npm install --save-dev amazeui-touch下报错误

### ISSUE THREAD

**Issue by 6875122qq** [amazeui/amazeui#896]
bogon:amazeui-touch-master myunite$ sudo npm install --save-dev amazeui-touch
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "amazeui-touch"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.6
npm ERR! code ENOSELF
 
npm ERR! Refusing to install amazeui-touch as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
 
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myunite/Downloads/amazeui-touch-master/npm-debug.log
bogon:amazeui-touch-master myunite$  

这是什么情况:
为什么mac下无法安装amazeui
为什么windows下执行npm run build通过?

**Comment by minwe** [comment]
```
npm ERR! Refusing to install amazeui-touch as a dependency of itself
```

不要在 `amazeui-touch` 源码目录里安装。
