### ISSUE TITLE
JS Tabs插件在form标签中无法切换内容

### ISSUE THREAD

**Issue by sidbusy** [amazeui/amazeui#899]
## 问题描述

JS Tabs插件在form标签中无法切换内容

## 产生环境

- **操作系统及版本：**OS X 10.11.5
- **浏览器及版本：**Chrome  51

## 复现步奏

将JS Tabs插件置于form标签中

**Comment by minwe** [comment]
请给出能重现问题的演示代码

http://bin.amazeui.org/kikobeqevo/edit?html,output 直接嵌套无法重现你说的问题。

**Comment by sidbusy** [comment]
我把tabs放回form标签内似乎又好了。之前同样的代码复制到form标签外就正常，放回form标签内就切换不了内容。再有发生我直接贴上来。谢谢。

**Comment by minwe** [comment]
那就先关闭了，遇到问题再重新打开吧。
