### ISSUE TITLE
JS: Sticky 底部距离选项计算逻辑有问题

### ISSUE THREAD

**Issue by minwe** [amazeui/amazeui#90]
当固定元素的高度加上底部边距的高度大于窗口高度时，固定元素的顶部被移除到视口之外

**Comment by minwe** [comment]
鉴于没有用户反馈此类需求，不再处理。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://weboss.net/female.php?pz>

 

Again_moon@sohu.com
