### ISSUE TITLE
2.7.1的modal内的元素的click事件被终止冒泡，造成一些不便

### ISSUE THREAD

**Issue by KuoKongQingYun** [amazeui/amazeui#900]
## 问题描述
amazeui.js里加了这么一段，看注释应该是额外不久前加入的

```javascript
// trigger dimmer click event if non-dialog area clicked
// fixes #882 caused by https://github.com/amazeui/amazeui/commit/b6be7719681193f1c4cb04af89cb9fd9f4422163

.on('click', function(e) {
	      e.stopPropagation();
	      $(e.target).is($element) && $dimmer.trigger('click.dimmer.modal.amui');
	    });
```

这段代码导致modal的按钮的click事件无法向上冒泡，而我写了一个js脚本用于处理提交按钮的click事件，使得表单通过ajax的方式提交，用的是$(document).on('click','xxx',function(){})，因为停止冒泡了，所以就导致这个委托就无效了。我想到了几种办法，但感觉都不太好：
1.直接删除e.stopPropagation();
但既然这段代码存在就应该有它的道理，直接删了可能会有其它问题（具体这段代码是干啥的没仔细看）。
2.使用modal的onConfirm来处理表单，但我整个网站所有的表单都是通过我写的那个js转为ajax提交的，单独为了modal把js里的内容复制一份放到onConfirm(当然也要做一些修改），也不太好，这样代码就出现冗余了。

我现在只能使用2.7.0的js库来临时避免这个问题了。

**Comment by minwe** [comment]
当时理解有点偏差，其实不需要 `stopPropagation`。

**Comment by chunsh** [comment]
如何进行临时处理呢

**Comment by minwe** [comment]
@chunsh 可以先降级回 `v2.7.0` 或者按楼主说的删除相应的 `e.stopPropagation();`

**Comment by m55z** [comment]
这问题，我也遇到了，暂时先删除  e.stopPropagation();

**Comment by CrazyStone8** [comment]
![qq 20161222104605](https://cloud.githubusercontent.com/assets/22724717/21413690/345a42ae-c834-11e6-97ed-e201aa3e68c7.png)
![qq 20161222104630](https://cloud.githubusercontent.com/assets/22724717/21413691/34609712-c834-11e6-96ea-22a62a90ab56.png)
点击确定按钮，用ajax进行处理数据，然后成功后,用.modal('close')关闭模态框，然后就出现第一个图的现象（那两个类没有进行移除），这个问题是因为什么原因呢？
