### ISSUE TITLE
段落组件（paragraph）使用

### ISSUE THREAD

**Issue by gongjingyi** [amazeui/amazeui#902]
paragraph这个组件在使用时出现了，有时候点击图片没效果的现象（问题很容易复现，不区分客户端），使用了$.AMUI.paragraph.init();之后测试暂时还没发现什么问题了。但是还不太明白其中的具体原理，担心有其他的问题出现。比如我插入了一个article文章节点，这个文章节点引用了这个组件。要使得点击这个文章里面的图片有效果，我是一定要等到我这个article文章节点里面的图片插入了，再调用初始化这个组件的方法才有效果。还是只需要在我这个article文章节点插入了之后调用初始化这个组件的方法就会有效果，而不用去关心他的子元素有没有插入？还望帮忙解答下，十分感谢！

**Comment by minwe** [comment]
默认的初始化行为在 DOM `ready` 的时候执行， 后来插入的内容已经过了这个时机，自然是不会初始化这些行为的，需要你插入以后手动去调用初始化接口。

**Comment by gongjingyi** [comment]
谢谢作者亲自解答【微笑】，【撇嘴】我也想知道后部分的一个问题，就是这个组件的更具体详细的使用，他涉及到我代码放置的位置和时间点。还是上面的问题，我在一个article文章节点上引用了paragraph这个组件，我要使我的文章里面的图片点击之后有效果（首先是插入了article这个文章节点，然后再发送请求向后台请求了数据之后再将图片插入到article文章节点中的），我的这行代码$.AMUI.paragraph.init();是只用放在append(article)这行代码之后，还是要等我向后台请求的图片插入到文章节点（append(img into article )）之后？求解答（关于这种图片点击效果的组件初始化的原理过程）

**Comment by minwe** [comment]
要先有 DOM 结构，然后 JS 才能找到相应的节点进行操作，所以应该在图插入文章节点以后再调用 `init()`。

具体可以实现可以查看源码 https://github.com/amazeui/amazeui/blob/master/widget/paragraph/src/paragraph.js。

**Comment by gongjingyi** [comment]
谢谢作者的认真的解答，一脸崇拜【痴笑】
