### ISSUE TITLE
显式调用组件的init()的时机是什么？

### ISSUE THREAD

**Issue by gongmingbin** [amazeui/amazeui#903]
组件初始化后异步重新插入了新的子节点是否还需要再次调用组件的init()函数？
或者说显式调用组件的init方法的时机是在插入组件节点之后还是在整个组件的子结构完整之后？
比如:
时机一：插入了组件

```html
<div data-am-widget="paragraph" class="am-paragraph am-paragraph-default" data-am-paragraph="{ tableScrollable: true, pureview: true }">
</div>
```

时机二：插入了图片子节点：

```html
<div data-am-widget="paragraph" class="am-paragraph am-paragraph-default" data-am-paragraph="{ tableScrollable: true, pureview: true }">
  <img src="http://s.amazeui.org/media/i/demos/bing-1.jpg data-rel="http://s.amazeui.org/media/i/demos/bing-1.jpg" data-am-pureviewed="1">
</div>
```

**那么，我应该是在时机一还是时机二（每次插入了新的图片）显式调用AMUI.paragraph.init()呢？
如果是一或者二的话，那么这种方案是视不同的组件不同还是amaze UI组件规范的一部分呢？**

**Comment by minwe** [comment]
**时机二**。

插件初始化是去找的是 `paragraph` 里图片，如果没有图片，就没有效果了。

- http://amazeui.org/widgets 这里面的组件都提供了 `init()` 接口。
- 其他 JavaScript 插件则可以自己调用相应 jQuery 方法初始化，如 `$('#my-dropdown').dropdown()`。
