### ISSUE TITLE
 Amaze UI 中 有没有状态栏？ 

### ISSUE THREAD

**Issue by dabing69221** [amazeui/amazeui#909]
## 问题描述

Amaze UI 中 有没有状态栏？

我想在 head 标题栏 下面增加一个 “状态栏”用于显示一些汇总信息，请问 amazeui 如何实现呢？ 在线等大神赐教，小弟不胜感激！！！
![error](https://cloud.githubusercontent.com/assets/20959956/17657079/231a5c32-62f3-11e6-8df3-fce09bf48f51.png)

**Comment by minwe** [comment]
没有现成的组件，自己加一个 `div` 简单设置一下样式就可以了。

**Comment by dabing69221** [comment]
@minwe 我想用 Sticky 插件 固定元素，但是滚动的时候，不会将元素固定在窗口顶部
<div data-am-sticky>
  <button class="am-btn am-btn-primary am-btn-block">Stick to top</button>
</div>

**Comment by minwe** [comment]
没有演示无法确定问题出在哪

你可以用 CSS `position: sticky` 自己实现：

https://github.com/filamentgroup/fixed-sticky
