### ISSUE TITLE
Bug: Amaze UI 移植插件 DataTables 响应式 文字显示不全，如何解决？ 

### ISSUE THREAD

**Issue by dabing69221** [amazeui/amazeui#910]
**问题描述**
Amaze UI 移植插件 DataTables 响应式 ，在移动端会产生单元格文字显示不全的问题，请问如何解决？@minwe

**产生环境**

- 设备：移动设备 Android / IOS

![qq 20160818083154](https://cloud.githubusercontent.com/assets/20959956/17758632/8eb5384a-6523-11e6-8d89-32933861cb11.png)

**Comment by minwe** [comment]
Duplicated with https://github.com/amazeui/datatables/issues/11.

**Comment by dabing69221** [comment]
@minwe 谢谢，问题已解决！
`/*修复datatables显示问题*/ function repairDataTables() { //修复“单元格”文字过长不自动折行问题 $('.am-text-nowrap').css('white-space','normal'); }`
