### ISSUE TITLE
Bug: Selected下拉选框组件动态加入option时,样式会消失

### ISSUE THREAD

**Issue by ending-sun** [amazeui/amazeui#911]
**问题描述**
   一开始创建类似 `<select data-am-selected></select>` 空组件,然后再通过js动态往里面加入option时，该组件的样式会消失，变成原始selecte组件的样子。

**产生环境**
- 设备：
- 操作系统及版本：
- 浏览器及版本：基本所有浏览器都有该问题
- 演示地址：

**复现步奏**
1. 创建类似 `<select data-am-selected></select>` 空组件
2. 通过js动态往里面加入option时，该组件的样式会消失，变成原始selecte组件的样子。
   ... 

**UA:** 

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7
```

**Comment by minwe** [comment]
没发现你说的问题：http://bin.amazeui.org/hequjepoxa/edit?html,output

更多细节参考文档：http://amazeui.org/javascript/selected#js-cao-zuo-select

如果还有问题请给出演示。

**Comment by dabing69221** [comment]
@minwe 我也遇到过该问题，我是通过handlebars 模板，动态添加 options 时，select样式确实会变成 原声的样式，非常难看，希望官方看看问题所在吧
