### ISSUE TITLE
Form样式失效

### ISSUE THREAD

**Issue by xfworld** [amazeui/amazeui#914]
![1](https://cloud.githubusercontent.com/assets/5020771/17922696/f7565cfa-6a12-11e6-8638-eb1404499ad1.png)

![2](https://cloud.githubusercontent.com/assets/5020771/17922699/fcb28ffc-6a12-11e6-939e-952fa200960d.png)

同时使用Form样式，和Jquery 插件Selected ；换行失效；
在Lable结束符，手动增加<code>代码 br 换行符</code>可以开启换行效果；
我用的AmazeUI的版本：2.5.2
是不是高版本的，已经解决这个问题了？

**Comment by lwxyfer** [comment]
Dropdown 是`display:inline-block` ; 而表单的 input 是 `block` ;  所以这个需要你自己换行。
