### ISSUE TITLE
模态窗口Popup，在IPhone5s真机上运行，标题框无法固定，显示错位？

### ISSUE THREAD

**Issue by dabing69221** [amazeui/amazeui#915]
## 问题描述

模态窗口Popup，在IPhone5s真机上运行，标题框无法固定，显示错位？
## 产生环境
- **设备及型号：IPhone5s
- **操作系统及版本：IOS9
- **浏览器及版本：Safari
  ![img_1136](https://cloud.githubusercontent.com/assets/20959956/18045988/42a850e8-6e08-11e6-9746-949b8a81463b.PNG)
  ![img_1137](https://cloud.githubusercontent.com/assets/20959956/18045986/41c187d0-6e08-11e6-9a22-acbc94b37ce5.PNG)

**Comment by dabing69221** [comment]
@minwe

**Comment by lwxyfer** [comment]
可能是外层的fixed定位造成的问题
