### ISSUE TITLE
模态窗口Popup，在IPhone真机上运行，标题框、确定取消按钮，下拉滚动严重错位？？ 

### ISSUE THREAD

**Issue by dabing69221** [amazeui/amazeui#916]
模态窗口Popup，在IPhone5s真机上运行，标题框、确定取消按钮，下拉滚动时错位？

问题描述：

模态窗口 Popup，在iPhone（5s/6） 手机上测试，内容滚动时，出现严重的错位问题？这里的标题、确定按钮使用的 position: fixed 样式，请问 amaze ui官方 如何解决该问题？

备注：该功能在 Android 手机上测试没有问题，IOS 手机上却出现严重错位？

CSS：
`/*popup:水平垂直居中*/
       .Absolute-Center {
          margin: auto;
          position: fixed;
          top: 0; left: 0; bottom: 0; right: 0;
        }
        /*popup:基本样式*/
        .am-popup-bd{
            padding: 0 0 0 15px;
        }
        .am-popup-hd .am-close{
            color: #333;
            opacity: 1;
        }
        /*popup:固定确定取消按钮*/
        .my-popup-footer{
            position: fixed;
            bottom: 0;
            z-index: 1000;
            width: 100%;
            border-top: 1px solid #dedede;
            background-color: #fff;
        }
        .my-popup-inner{
            padding-bottom: 45px;
        }`

HTML：

`
    <div class="am-popup Absolute-Center" id="my-popup-strength" style="height: 65%;width: 90%">
          <div class="am-popup-inner my-popup-inner">
            <div class="am-popup-hd">
                  <h4 class="am-popup-title">强度等级</h4>
                  <span data-am-modal-close class="am-close am-icon-close am-icon-sm"></span>
            </div>
            <div class="am-popup-bd">
                <div id="amz-strength"></div>
                <script type="text/x-handlebars-template" id="amz-strength-template">
                    {{#this}}
                    {{#each strength}}
                         <div class="am-fl" style="width: 50%;">
                              <label class="am-radio">
                                  <input type="radio" name="strengthRadio" value="{{{value}}}" data-am-ucheck>{{{display}}}
                            </label>
                          </div>
                    {{/each}}
                    {{/this}}
                </script>
            </div>
            <div class="am-modal-footer my-popup-footer">
                 <span class="am-modal-btn" data-am-modal-cancel>取消</span>
                  <span class="am-modal-btn" data-am-modal-confirm>确定</span>
            </div>
          </div>
    </div>`

截图看附件
![img_1138](https://cloud.githubusercontent.com/assets/20959956/18074832/543b2f0c-6ea2-11e6-8921-5115689f8e4d.PNG)
![img_1139](https://cloud.githubusercontent.com/assets/20959956/18074831/5215a798-6ea2-11e6-8a04-938d27bb3ad3.PNG)

**Comment by lwxyfer** [comment]
目前没有很好的解决方案，浏览器兼容性问题，若你有什么方法，也可以告诉我们。我们也会寻找是否有可替代方案。

**Comment by Dicooo** [comment]
在需要滚动的地方加个垂直滚动不就好了

**Comment by dabing69221** [comment]
@Dicooo 这个是 ios Safari 游览器适配问题，加什么垂直滚动都不好使，你自己可以试试

**Comment by Dicooo** [comment]
![msg](https://cloud.githubusercontent.com/assets/11000939/18299576/81e4e5d0-74f4-11e6-8ae7-d7ec07585f2d.png)

**Comment by dabing69221** [comment]
找了好长时间，原来是 外层滚动条 overflow : auto 导致的，调整为 overflow : hidden 后，显示正常不错位
