### ISSUE TITLE
Tabs内使用Chosen插件时的问题

### ISSUE THREAD

**Issue by zeroabc** [amazeui/amazeui#917]
## 问题描述

amazue ui 版本2.7.2

使用Chosen，当select展开的时候选项框被遮罩，

如果在 .am-tabs-bd 上添加 .am-tabs-bd-ofv的话，样式会有异常。

##截图

①
<a href="http://s1294.photobucket.com/user/zeroabc/media/it-temp/QQ20160901173944_zps2qcz36oq.jpg.html" target="_blank"><img src="http://i1294.photobucket.com/albums/b606/zeroabc/it-temp/QQ20160901173944_zps2qcz36oq.jpg~original" border="0" alt=" photo QQ20160901173944_zps2qcz36oq.jpg"/></a>

<a href="http://s1294.photobucket.com/user/zeroabc/media/it-temp/QQ20160901174029_zpshhxyfrpm.jpg.html" target="_blank"><img src="http://i1294.photobucket.com/albums/b606/zeroabc/it-temp/QQ20160901174029_zpshhxyfrpm.jpg~original" border="0" alt=" photo QQ20160901174029_zpshhxyfrpm.jpg"/></a>

②如果在 .am-tabs-bd 上添加 .am-tabs-bd-ofv：
<a href="http://s1294.photobucket.com/user/zeroabc/media/it-temp/QQ20160901173903_zpsqxfp3jtc.jpg.html" target="_blank"><img src="http://i1294.photobucket.com/albums/b606/zeroabc/it-temp/QQ20160901173903_zpsqxfp3jtc.jpg~original" border="0" alt=" photo QQ20160901173903_zpsqxfp3jtc.jpg"/></a>

## 代码
[http://sharetext.co/s/9126](url)

**Comment by lwxyfer** [comment]
http://bin.amazeui.org/jutena/edit?html,js,output  
你可以参考上面链接的解决方案，select高度不好处理，所以在触发tab后设置overflow为visible即可。

**Comment by zeroabc** [comment]
@lwxyfer 
这样处理之后确实没问题了，谢谢！！！
