### ISSUE TITLE
amazeUI2.7.2-简单的管理后台界面-左侧菜单栏无法收缩（从官网下载的AmazeUI-2.7.2.zip）

### ISSUE THREAD

**Issue by HuangYiXiang4680** [amazeui/amazeui#918]
[amazeUI2.7.2-简单的管理后台界面-左侧菜单栏无法收缩（从官网下载的AmazeUI-2.7.2.zip）.zip](https://github.com/amazeui/amazeui/files/453294/amazeUI2.7.2-.-.AmazeUI-2.7.2.zip.zip)

**Comment by lwxyfer** [comment]
下载包中未提供 jQuery，请确保正确引入了。

**Comment by HuangYiXiang4680** [comment]
好的，谢谢。
