### ISSUE TITLE
Bug: 官网天天打不开，卡的要死，不知道是不是天天被攻击

### ISSUE THREAD

**Issue by yaozhixing** [amazeui/amazeui#920]
**问题描述**

（描述一下问题）

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
```

**Comment by lwxyfer** [comment]
请确保你把域名写正确了； 
如果正确， 你可以提供你的所在的地区和电信运营商。
