### ISSUE TITLE
npm install 警告jQuery没有安装，导致预览失败

### ISSUE THREAD

**Issue by brantzf** [amazeui/amazeui#921]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN amazeui@2.7.2 requires a peer of jquery@^2.2.3 but none was installed.

**Comment by brantzf** [comment]
需要手工  `npm install jquery@^2.2.3`  文档写的真不让人省心

**Comment by minwe** [comment]
npm3 的机制就是这样的，都需要手动处理的。

自己的项目的话就把 jQuery 写在 `dependencies` 里。
