### ISSUE TITLE
Bug: 引入swfobject.js视频插件，模态窗口被遮挡

### ISSUE THREAD

**Issue by HuangYiXiang4680** [amazeui/amazeui#924]
**问题描述**
  引入swfobject.js视频插件，模态窗口被遮挡

**产生环境**
- 操作系统及版本：WIN7中文旗舰版 64位
- 浏览器及版本：火狐 49.0.1
- 演示地址：见附件

**复现步奏**
1. 解压bug.zip
2. 使用火狐浏览器打开admin-form.html
3. 点击“操作处理”按钮
[bug.zip](https://github.com/amazeui/amazeui/files/518741/bug.zip)

**Comment by HuangYiXiang4680** [comment]
有人么？能否解答一下呢？

**Comment by lwxyfer** [comment]
我这测试是模态窗口是正常的，另外浏览器可能不支持falsh，所以没有出现问题
