### ISSUE TITLE
Bug:footer表现诡异

### ISSUE THREAD

**Issue by wuji977746075** [amazeui/amazeui#926]
amazui.css 文件 中 body{position:relative} 造成 html和body高度在内容不够一屏时表现不一，此时footer表现诡异，去掉才可以正确显示

**Comment by wuji977746075** [comment]
对了，模板用了avalonjs 展现，还不知道与这个有关系没

**Comment by xfworld** [comment]
你应该把你的环境都写出来...

**Comment by lwxyfer** [comment]
http://bin.amazeui.org/?html,css,output  你贴下代码看看
