### ISSUE TITLE
Select插件存在问题

### ISSUE THREAD

**Issue by xfworld** [amazeui/amazeui#927]
我在使用jquery Selected插件时，出现一个问题；
当Select绑定了Change事件后，如下：

<pre><code>
$selected.on('change', function() {
        console.log('我被调用了');
  });
</code></pre>

在使用官方给出的API：
$('select').selected('destroy'): //销毁实例
// 使用默认参数
$('select').selected();  //初始化
![1](https://cloud.githubusercontent.com/assets/5020771/19301484/51a1870c-9092-11e6-8ac2-53dd621cd0ef.png)
调用以上两个API方法，如图中描述，会触发change事件.....

**Comment by lscho** [comment]
是的，因为在初始化和销毁的时候都会触发对select的操作。解决办法别的issue里有。$selected.off('change').on('change',fn)。在初始化之后再用off().on()绑定

**Comment by lwxyfer** [comment]
测试： http://bin.amazeui.org/lagomu/edit?html,js,console,output 
没有发现问题
