### ISSUE TITLE
Gallery 图片画廊使用反馈

### ISSUE THREAD

**Issue by chenjia404** [amazeui/amazeui#928]
**Gallery 图片画廊不支持超长图片**

打开一张长微博图片，页面宽度没有自适应，手机打开内容甚至会花。

**产生环境**
- 设备：通用
- 操作系统及版本：通用
- 浏览器及版本：通用
- 演示地址：http://weibo.wbdacdn.com/user/3099016097/

**复现步奏**

找一张长度几倍于屏幕的图片，点击查看。

**UA:** 

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2895.0 Safari/537.36
```

**Comment by lwxyfer** [comment]
宽度时自适应的 ， 另外确实不支持类似微博这样的超长滚动。手机打开会花，没遇到，你可以截屏上来看下。
