### ISSUE TITLE
string.indexOf抛出异常！

### ISSUE THREAD

**Issue by SpadeGod** [amazeui/amazeui#929]
## 问题描述

string.indexOf抛出异常！
## 产生环境
- **浏览器及版本：**（Chrome）
## 复现步骤

amazeui.js第269行

或者全文搜索 string.indexOf 

原代码：var start = (string ? string.indexOf('{') : -1);
问题描述： 当string对象不为String的时候，string.indexOf就会抛出异常
解决方案：使用string.toString()就可以解决这个问题（如下所示）

269 -  var start = (string ? string.indexOf('{') : -1);
269 + var start = (string ? string.toString().indexOf('{') : -1);

**Comment by lwxyfer** [comment]
这里传进入的就应该是 String 类型
