### ISSUE TITLE
表单验证的时候希望屏蔽掉原生的form提交，验证的时候希望返回一个状态，true,false

### ISSUE THREAD

**Issue by zhihuihu** [amazeui/amazeui#930]
表单验证的时候希望屏蔽掉原生的form提交，验证的时候希望返回一个状态，true,false
因为在表单验证后，还要做其他的操作，比如ajax请求，并不跳转页面，这个就不那么实用了

**Comment by lwxyfer** [comment]
可使用接口
```
// 域通过验证时回调
  onValid: function(validity) {
  },

// 定义表单提交处理程序
  submit: function() {
  }
```
你仔细看下文档，留有接口的。

**Comment by zhihuihu** [comment]
我看了文档，但是这两个方法，并不会执行呢，表单依然会像之前form一样的提交，并且刷新该页面，能不能不刷新该页面呢？

**Comment by zhihuihu** [comment]
写法和列子，一样，但是就是没有效果，依然表单提交了。

**Comment by lwxyfer** [comment]
submit 返回 false 即可。http://bin.amazeui.org/qeliha/edit?html,js,console,output
