### ISSUE TITLE
Modal 组件closeViaDimmer失效问题

### ISSUE THREAD

**Issue by loongier** [amazeui/amazeui#933]
是因为
.am-modal {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}
样式把 .am-dimmer 遮挡，导致点击失效。
但，目前这种布局方式，能够让.am-modal-dialog自动居中，很实用。
所以建议，closeViaDimmer属性在.am-modal仍然有效，而不需要将.am-modal的样式改回left:50%之类的

**Comment by minwe** [comment]
这个 2.7.2 中处理过了，https://github.com/amazeui/amazeui/commit/ef867ea4a5896ff50cb9c28494034bbcd3448b07#diff-c75f221c1439eec794cb34302712146dR243

还有问题？

**Comment by loongier** [comment]
不好意思，走错片场了，  这个问题在 amazeui-react 中出现
