### ISSUE TITLE
跟Jekyll下pandoc调用图片的语句有冲突？

### ISSUE THREAD

**Issue by i2000s** [amazeui/amazeui#934]
## 问题描述

我在一Ｊｅｋｙｌｌ网站下调用ＡｍａｚｅＵＩ２．７．２的ＣＤＮ，结果原来图片注释文字(caption,title)要么消失，要么宽度只有一个字符的大小，整个注释文字变成了长长的一纵列。网站使用Ｐａｎｄｏｃ的Markdown渲染图片等语句。如果将图片调用语句`![title](/path/to/image){#id class=xx; width=100px;}`放到`<center>...</center>`之间，｀title`的内容会直接消失。怀疑AmazeUI对ｃａｐｔｉｏｎ等属性有更改，或者没有考虑ｉｍａｇｅ调用Markdown的编译格式问题。

## 产生环境

- **设备及型号：**: desktop
- **操作系统及版本：**: Ubuntu 16.04
- **浏览器及版本：**:最新的Ｃｈｒｏｍｅ　54.0.2840.100 (64-bit)
- **演示地址：**：暂时没有完整的代码演示，但是可以按照复现步骤复现问题。
- **问题截图/录屏：**

　图一：正常情况（使用ｂｏｏｔｓｔｒａｐ。图示下的中文为注释内容。）
　
　![screenshot from 2016-12-05 00-14-17](https://cloud.githubusercontent.com/assets/3915003/20876786/9797008e-ba81-11e6-9a4e-8eb94626c6ff.png)

　图二：问题情况（使用ＡｍａｚｅＵＩ。图示下的英文为其下一段落正文。）
　![screenshot from 2016-12-05 00-24-16](https://cloud.githubusercontent.com/assets/3915003/20876753/61e79e3a-ba81-11e6-8889-49cb3f8621c4.png)

## 复现步奏

1.　`git clone https://github.com/i2000s/en.git`
2. 在`_include/header.html`文件的`<header>`部分末尾添加AmazeUI的css 和js的CDN链接并保存。
3.　编译jekyll网站：
```
bundle install
bundle exec jekyll serve
```
打开网页到`127.0.0.1:4000/en/`，点击Research菜单进入页面后即可看到图片注释文字消失（这里的注释应该是英文）或者变成一列。你看到的现象可能跟截图不一样，但是效果应当一致。

**Comment by lwxyfer** [comment]
amazeui 加载后覆盖掉你的自定义样式了， 你需要把 link，即样式加载顺序提前到你的 `<!-- Self-defined style -->` 前面

**Comment by i2000s** [comment]
@lwxyfer That works! Thank you for the trick.
