### ISSUE TITLE
开发停滞了？

### ISSUE THREAD

**Issue by baryon** [amazeui/amazeui#936]
下一步的计划是什么？

有没有要做For VUE, 特别是mobile专用的ui，最近出了很多，比如mint-ui
妹子加油

**Comment by lwxyfer** [comment]
内部开发中，多谢关注哦。

**Comment by xfworld** [comment]
@baryon react的版本还不够你用啊？

**Comment by baryon** [comment]
萝卜白菜各有所爱。至少amazeui应该出一个不依赖于react还是vue的，针对mobile的优化版本，特别是css部分。国内vue做前端的人气感觉比react好
2016年12月22日(木) 19:20 flying <notifications@github.com>:

**Comment by killkiss** [comment]
先把手机端组件兼容各方面做稳定再说吧！ISCOLL和FASKCLICK各种问题。比如多次触发click。

**Comment by lwxyfer** [comment]
有问题和建议可以在 https://github.com/amazeui/amazeui/issues/947  这里提吧。
