### ISSUE TITLE
在tab中内嵌select，选择 select 会切换 tab

### ISSUE THREAD

**Issue by zcdll** [amazeui/amazeui#938]
## 问题描述

通过 Data API 的方式 加载 tab 和 select，select 在 tab 中，当选择 select 时，会切换tab。

**Comment by zcdll** [comment]
选择 select 时 应该选 data-am-selected 而不是 data-am-dropdown，换过来就好了。

**Comment by zcdll** [comment]
- 在 vue 中，如果按照如下方式引入 select，发现不能获取 seleted 的值。
- 使用 tab，把 select 放到 某个 tab 时，如果去掉 select 的 data-am-selected 属性，则在选择 select **某一项后，会**自动进入**下一个 tab。
- 其中 tab 采用数据绑定的方式的引入。

我的理解是，既然去掉了 data-am-selected，那就应该是普通的 select 了，也就没有了 amazeui 的数据绑定。但是还会执行一次 tab 的数据绑定。

所以我怀疑是 amazeui 后台对于数据绑定 插件 的刷新 问题？

谢谢！

下面是代码

```
<select class="status-option" data-am-selected v-model="selected">
      <option v-for="option in typeOptions" v-bind:value="option.value">{{option.text}}</option>
    </select>
```

```
typeOptions:[
          {text: '待确认', value: '0'},
          {text: '待审核', value: '1'}
        ]
```

**Comment by lwxyfer** [comment]
你是指初始化的时候吗？ 按理说 Vue 中 select 如果没有设置默认值，就不会有选项。你贴下完整的代码吧，Vue 我不熟。

**Comment by xfworld** [comment]
@zcdll 你的应用场景是啥？其中 tab 采用数据绑定的方式的引入。怎么绑定的？
