### ISSUE TITLE
table的宽度会自动加上element.style

### ISSUE THREAD

**Issue by doinfi** [amazeui/amazeui#939]
table的宽度会自动加上element.style
本来设置好的宽度
![wechatimg1](https://cloud.githubusercontent.com/assets/9260958/21770980/8e3ec372-d6c0-11e6-8f43-efa90d7f2903.jpeg)

结果查询完数据，渲染以后表格的th自动加上了element.style，导致表格非常宽
渲染以后的表格样式
![wechatimg2](https://cloud.githubusercontent.com/assets/9260958/21770979/8e3e7f84-d6c0-11e6-970a-67094378ca96.jpeg)

其中宽度就是通过
“element.style {
    width: 1089.6px;
}”
加上的

**Comment by lwxyfer** [comment]
第一个 th， 你写成 `am-u-sm-200` 了。
