### ISSUE TITLE
select bug

### ISSUE THREAD

**Issue by Clark911** [amazeui/amazeui#941]
## 问题描述

select的maxHeight 和 searchBox 一起用时，列表显示位置错误，无法使用

## 产生环境

- **设备及型号：** PC
- **操作系统及版本：** Windows 7
- **浏览器及版本：** Chrome 51
- **演示地址：**
- **问题截图/录屏：**

**Comment by isLishude** [comment]
请给出代码吧

**Comment by Clark911** [comment]
&lt;select data-am-selected="{btnWidth:'100%', btnSize: 'lg', searchBox: 1}" name="position"&gt;
&lt;option value="无" selected&gt;请选择&lt;/option&gt;
&lt;option value="软件工程师"&gt;软件工程师&lt;/option&gt;
&lt;option value="CTO"&gt;CTO&lt;/option&gt;
&lt;/select&gt;

**Comment by lwxyfer** [comment]
我这测试是正确的。你描述清楚点，或者截张图
