### ISSUE TITLE
请问怎么样能屏蔽按ESC键关闭模态窗口Modal

### ISSUE THREAD

**Issue by yufanmn** [amazeui/amazeui#953]
## 问题描述

利用Modal自制的锁屏效果，但是发现一个bug，就是按下esc时锁屏界面消失，所以请问下如何屏蔽，是否有屏蔽接口？

## 产生环境

- **设备及型号：PC
- **操作系统及版本：win10
- **浏览器及版本：chrome最新版
- **演示地址：http://amazeui.org/javascript/modal
- **问题截图/录屏：**

## 复现步奏

1.进入页面http://amazeui.org/javascript/modal
2.点击1.1的Modal按钮，探出modal窗口
3.鼠标单击半透明处，即Dimmer上
4.键盘按下ESC
5.问题出现，modal被关闭

**Comment by stclair2201** [comment]
data-am-modal="{target: '#doc-modal-1', closeViaDimmer: 0,cancelable:false, width: 400, height: 225}"

**Comment by yufanmn** [comment]
@stclair2201 感谢stclair2201，ancelable:false确实可以解决问题，但需要使用使用Data API，我这边因为是ajax载入的，所以都是js调用，请教下应该怎么处理呢？谢谢！

**Comment by yufanmn** [comment]
@stclair2201 明白了，应该是下面这句，结帖，谢谢！
$('#mymodal').modal({closeViaDimmer: false,cancelable: false})
