### ISSUE TITLE
Bug: 贵站官网cdn的iconfont资源访问不到了

### ISSUE THREAD

**Issue by wisdom-yzh** [amazeui/amazeui#956]
**问题描述**

贵站官网cdn的iconfont资源访问不到了

**产生环境**

- 设备：all（手机、平板等移动设备时填写此项）
- 操作系统及版本：osx10.10
- 浏览器及版本：chrome
- 演示地址：http://cdn.amazeui.org/amazeui/2.7.2/fonts/fontawesome-webfont.woff2?v=4.6.3

**复现步奏**
![image](https://cloud.githubusercontent.com/assets/8413263/24463860/97556e0e-14da-11e7-8592-c2c4091dc458.png)
![image](https://cloud.githubusercontent.com/assets/8413263/24463883/a4ebbf82-14da-11e7-9261-d49312b0ecec.png)

 
**UA:** 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

**Comment by lwxyfer** [comment]
已修复。
