### ISSUE TITLE
amazeui-color负责人能否联系到？网站挂了

### ISSUE THREAD

**Issue by TylerTemp** [amazeui/amazeui#965]
请问<http://www.amazeui-color.com/> 是否能联系到？网站挂了，项目需要下代码，下不到。

如果不能，请直接关闭该issue

**Comment by minwe** [comment]
域名启用了隐私保护，查不到联系方式

https://whois.aliyun.com/whois/domain/amazeui-color.com

**Comment by TylerTemp** [comment]
感谢解答，以为是你们的子项目。
