### ISSUE TITLE
请求资料

### ISSUE THREAD

**Issue by xfworld** [amazeui/amazeui#967]
我在官网看到有col-md-3 的用法，但是手册和文档里面均没有提及，请问这块的资料能否补齐？

**Comment by isLishude** [comment]
走错地方了吧，这是 bootstrap的,对应amazeui的是 am-u-md-3

**Comment by minwe** [comment]
@xfworld

这是兼容老版本的代码，现在不需要关注了。

**Comment by xfworld** [comment]
@minwe 有多老的版本？来来，介绍下

**Comment by xfworld** [comment]
已经查过相关的资料了，可以关闭了；确实是版本遗留的问题；
