### ISSUE TITLE
OffCanvas怎么设置开启OffCanvas侧边栏的时候怎么去掉遮罩层

### ISSUE THREAD

**Issue by colodoo** [amazeui/amazeui#989]
## 问题描述

开启OffCanvas时候body部分会多一个遮罩层，怎么去掉该遮罩层。

## 产生环境

- **设备及型号：** 
- **操作系统及版本：** Win7
- **浏览器及版本：** Firefox 55.0.2 (32 位)
- **演示地址：** 
- **问题截图/录屏：** 

## 复现步奏
打开OffCanvas侧边栏，主体有遮罩层

**Comment by lwxyfer** [comment]
没有提供此接口。
