### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by wang1778630294** [amazeui/amazeui#991]
**问题描述**
       amazeui的轮播图组件在图片为三张的时候，每次最后一张向第一张滚动的时候会出现闪屏（个人试了两张图  四张图  五张图  都没有这个问题）
（描述一下问题）

**产生环境**
       谷歌浏览器
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：
<div class="am-slider am-slider-default" data-am-flexslider>
  <ul class="am-slides">
    <li><img src="http://s.amazeui.org/media/i/demos/bing-1.jpg" /></li>
    <li><img src="http://s.amazeui.org/media/i/demos/bing-2.jpg" /></li>
    <li><img src="http://s.amazeui.org/media/i/demos/bing-1.jpg" /></li>
  </ul>
</div>
**复现步奏**

1.  在编辑器上编写好代码;
2. 用谷歌浏览器打开
3. 当最后一张轮播向第一张的时候，会有明显的闪屏;
...

**Comment by wang1778630294** [comment]
希望能够快速处理,可以给予我反馈；
   感谢。

**Comment by HaoLeiQ** [comment]
六张图有问题吗
