### ISSUE TITLE
下拉选框宽度不随网格系统重新计算宽度

### ISSUE THREAD

**Issue by flyingl** [amazeui/amazeui#996]
## 问题描述

下拉选框宽度不随网格系统重新计算宽度（拖动浏览器，改变浏览器宽度大小，网格系统会重新计算宽度，单下拉选框不重新计算导致长度溢出）。

## 产生环境

- **设备及型号：PC
- **操作系统及版本：windows7
- **浏览器及版本：google 61.0.3163.100（正式版本） （64 位）
- **问题截图/录屏：**

**Comment by lwxyfer** [comment]
宽度初始固定，可以手动修改。
